// JourneysOfAwakeningUniversalEnergies.swift
// Module 13: Universal Energies — One Force, Many Names
// "We call it different things but we're all the same."
// Chi. Prana. Kundalini. Orgone. Ether. Mana. Divine Energy. Astral Energy.
// Different cultures. Different centuries. Same current.
// The biggest enemy isn't another fractal. It's your own ego.
// ☀️ SunFlow: Reignited

import SwiftUI

// MARK: - ═══════════════════════════════════════════════════
// MODULE 13: UNIVERSAL ENERGIES — ONE FORCE, MANY NAMES
// ═══════════════════════════════════════════════════════════

extension JourneysOfAwakeningCourse {
    
    static let module13_UniversalEnergies = AwakeningModule(
        id: "joa_m13",
        number: 13,
        title: "Universal Energies",
        subtitle: "One force. Many names. We are not separate.",
        emoji: "⚡",
        estimatedMinutes: 75,
        lessons: [
            
            // ═══════════════════════════════════════
            // LESSON 1: The Pattern Nobody Talks About
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m13_l1",
                number: 1,
                title: "The Pattern Nobody Talks About",
                subtitle: "Every culture felt the same thing",
                emoji: "🌍",
                sections: [
                    AwakeningSection(heading: "One Current, Eight Names", body: "Here's something that should stop you in your tracks.\n\nThe ancient Chinese called it Chi.\nThe ancient Indians called it Prana.\nThe yogis called its coiled form Kundalini.\nAn Austrian scientist called it Orgone.\nThe Greeks called it Ether.\nThe Polynesians called it Mana.\nThe Christians called it the Holy Spirit.\nThe mystics called it Divine Energy.\nThe occultists called it Astral Energy.\n\nDifferent continents. Different millennia. Different languages. Zero contact between most of these cultures.\n\nAnd they all described the same thing: an invisible force that flows through everything, connects everything, and animates everything. A universal current that you can't see with your eyes but can feel in your body when you're deeply focused, calm, or alive with purpose.\n\nThey described it flowing through the human body in channels — the Chinese mapped meridians, the Indians mapped nadis, the Kabbalists mapped the Tree of Life. They described it flowing through nature — in sunlight, water, earth, wind. They described it flowing through the cosmos — connecting stars, planets, and consciousness itself.\n\nThey said when this energy flows freely, you're healthy, clear, and aligned. When it gets blocked, you feel sick, stuck, anxious, or dead inside.\n\nThey built entire systems of medicine, martial arts, meditation, and spiritual practice around unblocking this flow.\n\nAnd here's the part that changes everything: if every culture on Earth independently discovered the same invisible force... maybe it's not mythology. Maybe they were all measuring the same reality with different instruments."),
                    AwakeningSection(heading: "Why This Matters More Than You Think", body: "This isn't just an interesting historical footnote. It's the key to the biggest realization in this entire course.\n\nIf the same energy flows through EVERYTHING — through you, through me, through every person on every continent in every era — then separation is an illusion.\n\nWe're not different races. We're the same energy expressing itself through different bodies shaped by geography, climate, and time.\n\nWe're not different religions. We're the same consciousness reaching for the same source using different languages.\n\nWe're not different species of human. We're fractals of the whole — individual expressions of one unified field, experiencing the universe through billions of unique perspectives simultaneously.\n\nYou are the universe looking at itself through your eyes.\nI am the universe looking at itself through mine.\nShe is the universe looking through hers.\nThey are the universe looking through theirs.\n\nWe are not drops in the ocean. We ARE the ocean, temporarily expressing itself as drops.\n\nOnce you see this — really see it, not just intellectually understand it — you can't hate anyone. How do you hate yourself? Because that's what hating another person is. It's one fractal of the whole attacking another fractal of the same whole.\n\nThere would be no wars if everyone saw this. There CAN'T be wars when you realize the enemy is you, wearing a different face, born in a different place, carrying different trauma, running different shadow code — but animated by the exact same force.\n\nThe only thing preventing this realization? Ego. That loud, persistent voice telling you that you're separate. That you're special. That you're different. That THEY are different. That you need to compete, dominate, defend, and validate your existence against other fractals of yourself.\n\nShut up already.\n\nLet's look at each energy system and see the same current flowing through all of them."),
                ],
                reflectionPrompt: "If I genuinely believed every person I meet is the same energy expressing itself differently — how would I treat the next person who annoys me?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 2: Chi, Prana & the Body Current
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m13_l2",
                number: 2,
                title: "Chi & Prana — The Life Current",
                subtitle: "Two cultures. Same map of the human energy body.",
                emoji: "🌬️",
                sections: [
                    AwakeningSection(heading: "Chi (Qi) — The Chinese Map", body: "Chi is one of the oldest concepts in human civilization. It literally means \"vital breath\" or \"life force.\"\n\nThe ancient Chinese said Chi is the universal current that flows through your body, through nature, and through the cosmos. It rides on your breath but it's not your breath. It flows through your blood but it's not your blood. It's the invisible current that makes the difference between a living body and a corpse.\n\nThey mapped it flowing through pathways called meridians — 12 main channels, each connected to an organ system (lungs, heart, liver, spleen, kidneys). When Chi flows freely through these meridians, you're healthy. When it gets blocked — by stress, trauma, bad diet, suppressed emotions — the blockage creates disease downstream.\n\nThis isn't ancient superstition. This is the foundation of Traditional Chinese Medicine, which has been practiced continuously for over 2,000 years and currently serves billions of people. Acupuncture — inserting needles at specific meridian points to unblock Chi flow — is now accepted by Western medicine for pain management and is covered by many insurance plans.\n\nChi isn't just inside you. It's everywhere:\n• In food (fresh, living food has more Chi than processed food)\n• In sunlight and nature (why being outdoors feels rejuvenating)\n• In breath (Qigong = the practice of cultivating Chi through breathing)\n• In movement (Tai Chi = moving meditation that circulates Chi)\n• In martial arts (internal power cultivated and directed through intention)\n\nModern research: While science can't directly measure Chi, it CAN measure what Chi practices produce — changes in heart-rate variability, brain wave patterns, immune function, inflammatory markers, and stress hormones. Qigong meta-analyses show significant effects on anxiety, depression, and chronic pain."),
                    AwakeningSection(heading: "Prana — The Indian Map", body: "Prana is Chi's Indian cousin. Same concept. Different map.\n\nIn Sanskrit, prana literally means \"life force\" or \"vital breath.\" The ancient yogis said everything in existence — every person, tree, star, and thought — contains prana. It's what turns a body from a structure of bones and tissue into a living, conscious being.\n\nPrana flows through thousands of subtle energy channels called nadis. Three are primary:\n\n• Ida — the left channel (lunar, cooling, feminine, intuitive)\n• Pingala — the right channel (solar, heating, masculine, analytical)\n• Sushumna — the central channel (where Kundalini rises when awakened)\n\nWhen prana flows equally through all three nadis, the body becomes balanced, the mind clears, and higher states of consciousness become accessible.\n\nPranayama — conscious breathing practice — is the technology for controlling prana. Each breathing pattern changes how energy flows:\n• Slow, deep breathing calms the system (parasympathetic activation)\n• Rapid breathing energizes (sympathetic activation)\n• Alternate nostril breathing (Nadi Shodhana) balances ida and pingala\n\nThe yogis also mapped prana into five types (Pancha Vayus):\n• Prana Vayu — energy that moves inward (breath, nourishment)\n• Apana Vayu — energy that moves downward (elimination, grounding)\n• Samana Vayu — balancing energy in the center (digestion, integration)\n• Udana Vayu — rising energy (speech, growth, ascending consciousness)\n• Vyana Vayu — energy that circulates everywhere (distribution, coordination)\n\nThese five operate like a management team running your energetic body — each handling a department.\n\nNow notice: the Chinese mapped 12 meridians connecting to organs. The Indians mapped thousands of nadis with three primary channels. Different system. Same observation: life force flows through the body in specific pathways, and blockages in those pathways cause physical, emotional, and mental dysfunction.\n\nModern parallel: Biofield science, bioelectromagnetics, heart-rate variability research, and vagus nerve stimulation studies all measure physiological systems that correspond to what Chi and Prana traditions describe."),
                ],
                reflectionPrompt: "Have I ever felt energy move in my body — tingling during meditation, heat rising up the spine, a 'buzzing' in my hands? What if that wasn't random but prana/chi flowing through my system?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 3: Kundalini, Orgone & Ether
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m13_l3",
                number: 3,
                title: "Kundalini, Orgone & Ether",
                subtitle: "The serpent power, the banned scientist, and the fifth element",
                emoji: "🐍",
                sections: [
                    AwakeningSection(heading: "Kundalini — The Coiled Serpent", body: "If Chi and Prana are the river, Kundalini is the dam breaking.\n\nKundalini is described as a coiled serpent of energy resting at the base of the spine — dormant in most people, waiting. Not metaphorically. The ancient yogis said a real current of divine energy lies coiled three and a half times around the base chakra (muladhara).\n\nWhen awakened — through meditation, breathwork, yoga, trauma, or sometimes spontaneously — this serpent rises through the central channel (sushumna), piercing each chakra:\n\n1. Root (survival, grounding)\n2. Sacral (creativity, sexuality)\n3. Solar Plexus (power, will)\n4. Heart (love, compassion)\n5. Throat (expression, truth)\n6. Third Eye (intuition, vision)\n7. Crown (unity, cosmic consciousness)\n\nWhen it reaches the crown, the individual consciousness (Shakti) merges with universal consciousness (Shiva). That's the state called samadhi — the experience of being everything.\n\nBut Kundalini awakening isn't always blissful. We covered this in Module 4. When the energy rises too fast or through unprepared channels, it can unleash repressed emotions, physical symptoms (tremors, heat, electrical sensations), and psychological upheaval. That's the Kundalini crisis — the energy is real, the body isn't ready.\n\nNeuroscience parallel: Some researchers compare Kundalini activation to a massive stimulation of the entire autonomic nervous system — sympathetic and parasympathetic firing simultaneously, creating the paradoxical experience of extreme alertness + deep peace.\n\nThe connection: Kundalini IS prana/chi in its most concentrated, potent form. It's not a different energy — it's the same life force, coiled and compressed, released all at once. Like the difference between a stream and a fire hose."),
                    AwakeningSection(heading: "Orgone — The Banned Discovery", body: "In the 1930s, an Austrian psychoanalyst named Wilhelm Reich claimed he'd discovered the same energy Western science had been denying for centuries. He called it Orgone.\n\nReich was a legitimate scientist — trained under Freud, published in peer-reviewed journals, ran clinical studies. He believed he'd found the cosmic life force that ancient cultures had always described — Chi, Prana, Ether — but dressed in scientific measurement.\n\nHe claimed Orgone could be measured, concentrated, and directed. He built devices called Orgone Accumulators — boxes made of alternating layers of metal and organic material that he said could collect life-force energy from the atmosphere.\n\nHe also built Cloudbusters — devices aimed at the sky that he claimed could influence weather by manipulating Orgone flow. According to multiple witnesses, they sometimes worked.\n\nReich connected Orgone to emotional and physical health. He observed that suppressed emotions — particularly suppressed sexuality and anger — created \"body armor\" (muscular tension patterns) that blocked Orgone flow. Release the emotional blockage, and the energy flows again.\n\nSound familiar? That's literally the shadow stored in the body. That's literally Chi/Prana blockage causing disease. Same observation. Different decade. Different continent.\n\nWhat happened to Reich: The US government declared his work fraudulent. They seized his equipment, BANNED HIS BOOKS, and BURNED HIS RESEARCH — one of the largest scientific censorship events in modern American history. Reich was imprisoned. He died in prison in 1957.\n\nWhether Orgone was \"real\" in the way Reich claimed, or whether he was measuring something we don't yet have instruments for, the pattern is clear: the same life-force concept keeps emerging across cultures and centuries, and institutional power keeps suppressing it.\n\nDraw your own conclusions."),
                    AwakeningSection(heading: "Ether — The Fifth Element", body: "Before atoms, before dark matter, before quantum fields — the ancients said the universe was filled with a pure, invisible substance that held everything together. They called it Ether.\n\nTo the Greeks, Ether was the fifth element — beyond earth, air, fire, and water. Aristotle said it was eternal, weightless, and unchanging. It filled the heavens, carried the light of stars, and connected the physical world to the divine.\n\nFor centuries, scientists used Ether to explain how light traveled through space. Sound needs air to propagate. Surely light needs a medium too? Ether was that medium — an invisible sea filling all of space.\n\nThen in 1887, the Michelson-Morley experiment tried to detect Ether by measuring how light moved through space. They found nothing. No drag, no flow, no Ether wind. Einstein's relativity replaced the need for a medium — space-time itself could bend and wave.\n\nScience declared Ether dead.\n\nBut spiritually, Ether never died. Mystics, alchemists, and Hermeticists kept it alive as the subtle field connecting mind and matter. What they called the \"luminous spirit.\" What modern metaphysics sometimes calls the zero-point field.\n\nAnd here's the twist: modern physics discovered that \"empty\" space isn't empty. The quantum vacuum is seething with energy — virtual particles appearing and disappearing, zero-point fluctuations, quantum fields permeating every point in space.\n\nScience killed Ether and then discovered... something remarkably like Ether. They just gave it different names: quantum vacuum, zero-point energy, dark energy, Higgs field.\n\nThe ancient map wasn't wrong. The instrument to measure it just hadn't been invented yet."),
                ],
                reflectionPrompt: "What pattern am I seeing across Chi, Prana, Kundalini, Orgone, and Ether? Is it possible they're all describing the same phenomenon from different angles?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 4: Mana, Divine & Astral Energy
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m13_l4",
                number: 4,
                title: "Mana, Divine & Astral Energy",
                subtitle: "From Polynesian islands to the cosmos itself",
                emoji: "🌊",
                sections: [
                    AwakeningSection(heading: "Mana — Spiritual Power That Can Grow or Fade", body: "Mana comes from Polynesian and Melanesian cultures. It means something like spiritual power or divine influence. But it's not a god. It's not magic. It's the force that flows through all living and non-living things.\n\nWhat makes Mana unique: it's not fixed. It can grow or shrink based on your actions.\n\nChiefs, warriors, and healers were said to have strong Mana. But it wasn't inherited — it was earned and maintained. If you were brave, honorable, and wise, your Mana grew. If you acted selfishly or broke sacred laws, your Mana weakened.\n\nMana was both spiritual energy AND moral currency. Your power was directly tied to your integrity.\n\nThis maps to something every awakening tradition describes: as you do inner work (shadow integration, meditation, ethical living), your \"energy\" increases. Your presence becomes more powerful. People feel it when you walk in the room. Your decisions carry more weight. Your words land differently.\n\nThat's not metaphor. Something is measurably changing — call it Mana, call it coherence, call it integrated presence. The Polynesians quantified what the mystics felt.\n\nMana also existed in objects and places. A warrior's weapon, a sacred stone, a particular beach or mountain — they could carry Mana. This maps to every tradition's concept of sacred spaces and objects. The energy isn't in the thing — it's the accumulated intention and consciousness directed at it.\n\nExplorers who arrived in the Pacific Islands noticed Mana wasn't tied to any single religion. It appeared in Hawaiian Huna, in Maori philosophy, in Melanesian practice. It was how people explained charisma, leadership, luck, and healing ability. A person with strong Mana could lead naturally, heal others, or create change just by their presence.\n\nSound like someone who's done deep integration work? That's what it looks like from the outside."),
                    AwakeningSection(heading: "Divine Energy — The Source Behind All Sources", body: "If Chi, Prana, Kundalini, Orgone, Ether, and Mana are rivers — Divine Energy is the ocean they all flow from.\n\nEvery culture has a name for it:\n\n• Hinduism: Shakti — the raw creative power of the universe, the feminine pulse that gives birth to all form\n• Christianity: The Holy Spirit — the breath of God that moves over the waters of creation\n• Hermetic philosophy: The Logos — the divine word or vibration that speaks matter into existence\n• Islam: Nur — the divine light\n• Judaism: Shekinah — the dwelling presence of God\n• Indigenous traditions: The Great Spirit, the Great Mystery\n\nUnlike the other energies that can be cultivated or directed, Divine Energy isn't controlled — it's surrendered to. You don't summon it. You align with it. When your mind quiets, your heart opens, and your intentions match truth, it flows through you effortlessly.\n\nThat's why saints, prophets, and healers across history all describe the same feeling: they didn't DO the miracle. Something greater moved through them.\n\nIn modern terms: Divine Energy is the frequency of pure coherence where love, truth, and creation are one. It's what turns chaos into order, darkness into light, and possibility into reality.\n\nThis is Unity Consciousness (Stage 7) experienced not as a state of mind but as an energy. The boundary between \"you\" and \"the divine\" dissolves because the boundary was always artificial. You ARE the divine, temporarily forgetting itself in order to experience itself from a unique perspective.\n\nThat's what incarnation is. The whole becoming a part, in order to experience partness, and eventually remember wholeness. That's the journey. That's every journey."),
                    AwakeningSection(heading: "Astral Energy — The Dream Current", body: "Astral energy is the current that runs the planes you can't see — the invisible force that powers dreams, visions, out-of-body experiences, and every experience beyond the physical.\n\nIf your physical body runs on food and oxygen, your astral body runs on this energy. It's the battery of the non-physical self.\n\nThe traditions:\n• Hinduism: Part of the linga sharira — the subtle body that mirrors the physical\n• Theosophy/Hermeticism: The astral double — the layer of consciousness that travels in dreams\n• Kabbalah: Ruach — the emotional force that binds spirit to matter\n\nAstral energy flows through your emotional frequency. When you're peaceful and loving, it's bright and easy to move through. When you're angry, fearful, or obsessed, it becomes dense — pulling your awareness back into the physical plane.\n\nThat's why every spiritual teacher stresses emotional purification. Not because anger is \"bad\" — but because unprocessed emotion creates density that blocks your access to subtler layers of reality. Shadow work isn't just psychology. It's energy work. Clear the emotional blockage, and awareness naturally expands into the astral and beyond.\n\nThis connects directly to the Planes module (Module 6). The astral plane is Floor 3. Astral energy is the current that carries your awareness to that floor. Your emotional state determines whether the elevator goes up or stays stuck.\n\nModern parallel: Lucid dreaming research shows that emotional state directly affects dream content and clarity. Meditation practitioners report more vivid, meaningful dreams. The correlation between emotional processing and dream quality is measurable."),
                ],
                reflectionPrompt: "Which energy concept resonated most — Mana (earned spiritual power), Divine Energy (surrendering to the source), or Astral Energy (the dream current)? What does that say about where I am on the journey?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 5: The Map & The Message
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m13_l5",
                number: 5,
                title: "One Force. One Family.",
                subtitle: "The map that ends all wars",
                emoji: "🤝",
                sections: [
                    AwakeningSection(heading: "The Complete Map", body: "Let's see them all together:\n\n🌬️ CHI (China) — Life force flowing through meridians. When blocked: disease. When flowing: health and harmony. Practice: Qigong, Tai Chi, acupuncture.\n\n🕉️ PRANA (India) — Vital breath flowing through nadis. Five types managing different systems. Practice: Pranayama, yoga, meditation.\n\n🐍 KUNDALINI (India) — Concentrated life force coiled at the spine base. When awakened: rises through chakras to cosmic consciousness. Practice: Kundalini yoga, breathwork, meditation.\n\n⚡ ORGONE (Western) — Universal life energy. Suppressed emotions block it. Reich measured and concentrated it. Practice: Emotional release, body-oriented therapy.\n\n🌌 ETHER (Greek/Universal) — The fifth element. Invisible substrate of reality. \"Killed\" by science, reborn as quantum vacuum. Practice: Contemplation, presence, stillness.\n\n🌊 MANA (Polynesian) — Spiritual power earned through integrity. Grows with right action, shrinks with wrong action. Practice: Ethical living, courage, service.\n\n✨ DIVINE ENERGY (Universal) — The ocean all rivers flow from. Not controlled but surrendered to. Practice: Prayer, devotion, surrender, alignment.\n\n💫 ASTRAL ENERGY (Esoteric) — The current powering non-physical experience. Flows through emotional frequency. Practice: Dream work, meditation, emotional purification.\n\nEight names. Eight cultures. One observation:\n\nReality is animated by an invisible force that flows through everything, connects everything, and responds to consciousness. Block it and you suffer. Allow it and you thrive. Direct it and you create. Surrender to it and you become it."),
                    AwakeningSection(heading: "The Message Behind the Map", body: "This module isn't really about energy systems. It's about what the energy systems PROVE.\n\nIf the same force flows through every living thing, then separation is the biggest lie ever told.\n\nThink about it:\n\nRacism? An illusion. We're not different races — we're the same energy expressing through bodies adapted to different geographies. The melanin in your skin is an adaptation to sunlight. That's it. Under the skin, the same Chi, the same Prana, the same life force flowing through the same channels. Genetically, any two humans are 99.9% identical. The 0.1% difference is the ego's excuse for 10,000 years of war.\n\nNationalism? An illusion. Borders are lines drawn on maps by people who wanted to control resources. The Chi flowing through a child in El Salvador is identical to the Chi flowing through a child in Norway. The Prana animating a farmer in Nigeria is the same Prana animating a programmer in Tokyo.\n\nReligious conflict? An illusion. The Christians, the Muslims, the Hindus, the Buddhists, the indigenous practitioners — they ALL described the same energy. They just gave it different names and built different rituals around it. Fighting over which name is correct is like fighting over whether to call water \"agua\" or \"mizu\" or \"eau.\" It's still water.\n\nThe ego — YOUR ego, MY ego, everyone's ego — is the ONLY thing maintaining the illusion of separation. It's the voice that says:\n\n\"I'm different.\"\n\"They're different.\"\n\"We're better.\"\n\"They're dangerous.\"\n\"I need to be validated.\"\n\"I need to win.\"\n\nShut. Up. Already.\n\nOnce you're conscious — truly conscious, not just intellectually aware but EXPERIENTIALLY awake — you see that every person you meet is you wearing a different face. Every conflict is self-harm. Every act of hatred is a fractal of the whole attacking itself.\n\nYou can't unsee it once you see it.\n\nAnd when enough people see it — when enough fractals remember they're part of the same whole — the systems that profit from division collapse. Not through revolution. Through recognition.\n\nThat's not naive idealism. That's the logical conclusion of the data. Every tradition on Earth arrived at the same finding: we are one. The energy proves it. The maps prove it. The math proves it. The experience proves it.\n\nThe question isn't whether it's true.\nThe question is whether you're ready to live like it's true.\n\nBecause if you are — you just changed the world. Not by fighting. Not by protesting. Not by posting. By BEING. By walking through your life as a conscious fractal that remembers the whole.\n\nThat's what awakening is.\nThat's what this entire course has been pointing at.\nEvery tradition. Every path. Every energy. Every plane. Every shadow. Every equation.\n\nOne truth. Infinite expressions.\nWe are not separate.\nWe never were. 🌅"),
                ],
                reflectionPrompt: "If I fully accepted that separation is an illusion and every person is the same energy in a different body — what would I change about my life starting tomorrow?"
            ),
        ]
    )
}
