// JourneysOfAwakeningShadowEngineers.swift
// Unit 7B: Shadow Work for Engineers — The Technical Deep Dive
// "I didn't believe in the Bible. I didn't know what shadow work was.
//  But once you look at it in terms of code... well, makes sense." — Ron
// For every engineer, scientist, and skeptic who needs the WHY before the HOW.
// ☀️ SunFlow: Reignited

import SwiftUI

// MARK: - ═══════════════════════════════════════════════════
// MODULE 7B: SHADOW WORK FOR ENGINEERS (EXPANDED)
// ═══════════════════════════════════════════════════════════

extension JourneysOfAwakeningCourse {
    
    static let module7b_ShadowEngineers = AwakeningModule(
        id: "joa_m7b",
        number: 8,
        title: "Shadow Work for Engineers",
        subtitle: "Your mind is codebase. Time to read the source.",
        emoji: "💻",
        estimatedMinutes: 80,
        lessons: [
            
            // ═══════════════════════════════════════════════════
            // LESSON 1: "I Didn't Believe in Any of This"
            // ═══════════════════════════════════════════════════
            AwakeningLesson(
                id: "joa_m7b_l1",
                number: 1,
                title: "I Didn't Believe in Any of This",
                subtitle: "How a senior iOS engineer found the most important codebase",
                emoji: "🤨",
                sections: [
                    AwakeningSection(heading: "Let Me Be Honest With You", body: "I didn't grow up religious. I didn't read the Bible. I didn't meditate. I didn't do yoga. I was an engineer. I solved problems with logic, architecture, and code. If you couldn't prove it, measure it, or debug it, I wasn't interested.\n\nSo when someone first mentioned \"shadow work\" to me, I literally said: \"What?\"\n\nShadow? Like... my physical shadow? A dark side? Star Wars stuff? What does this have to do with my actual life?\n\nAnd then someone explained it in a way that hit different. They said:\n\n\"Your mind is a codebase. You've been writing code since childhood — every experience, every trauma, every belief your parents handed you, every rule school drilled into you. Most of that code is running in the background right now. You've never reviewed it. You've never refactored it. And it's causing bugs in production.\"\n\nThat's when it clicked.\n\nI'm a senior iOS engineer. I've built apps with hundreds of thousands of lines of code. I know what happens when legacy code runs unchecked. I know what happens when you inherit a codebase nobody documented. I know what technical debt does to a system over time.\n\nShadow work is just... applying those same skills to yourself."),
                    AwakeningSection(heading: "Why Engineers Need This Most", body: "Here's the irony. Engineers are trained to debug EXTERNAL systems all day — find the root cause, trace the stack, fix the logic error, ship the patch. We're world-class at it.\n\nBut we never turn those skills inward.\n\nInstead, we:\n• Overwork instead of feeling (\"I'll just code until midnight, that'll fix the anxiety\")\n• Intellectualize instead of processing (\"I understand WHY I'm angry\" ≠ actually processing anger)\n• Optimize everything external while our internal system crashes silently\n• Wonder why we keep hitting the same walls — same relationship patterns, same burnout cycles, same impostor syndrome episodes\n\nAnd then someone says \"have you tried shadow work?\" and we roll our eyes because it sounds like crystal-waving nonsense.\n\nBut it's not. It's the most rigorous debugging protocol you'll ever run. And unlike your production app, this system has been accumulating technical debt for 20, 30, 40 years with ZERO code review.\n\nLet me show you the architecture."),
                ],
                reflectionPrompt: "What's my gut reaction to the idea of examining my own psychology? Skepticism? Discomfort? Curiosity? That reaction itself is data."
            ),
            
            // ═══════════════════════════════════════════════════
            // LESSON 2: Your Mind as a Codebase
            // ═══════════════════════════════════════════════════
            AwakeningLesson(
                id: "joa_m7b_l2",
                number: 2,
                title: "Your Mind as a Codebase",
                subtitle: "Architecture, memory leaks, and legacy code",
                emoji: "🏗️",
                sections: [
                    AwakeningSection(heading: "The Architecture", body: "Let's map it.\n\nCONSCIOUS MIND = Your IDE\nThe code you can see. Your active thoughts, decisions, current focus. This is maybe 5-10% of total processing. You think this is \"you.\" It's the tip.\n\nSUBCONSCIOUS = Background Processes\nHabits, emotional reactions, muscle memory, learned behaviors. Runs without your input. You set these up years ago and forgot. Like cron jobs from 2009 that are still executing.\n\nSHADOW = Hidden/Suppressed Code\nThis is the code that was deliberately pushed out of the main branch. Not deleted — HIDDEN. Moved to a private repo you don't have access to. Except it's still executing. Still allocating memory. Still affecting output. You just can't see it in your IDE.\n\nCOLLECTIVE UNCONSCIOUS = The Operating System\nJung's deepest layer. Think of it as the OS your individual app runs on — universal human patterns (archetypes) that every human shares. Status-seeking, belonging needs, threat detection, hero/villain narratives. You didn't write this code. Evolution did. It ships with every human.\n\nNow here's the problem: your Shadow is full of code that was written by a 5-year-old, a 12-year-old, a scared teenager — versions of you that didn't have your current skills. But that code is still in production. Running your emotional responses. Shaping your relationships. Making decisions you think are rational but are actually just... legacy code firing."),
                    AwakeningSection(heading: "Common Bugs in the Engineer's Shadow", body: "Let me get specific because I've lived these:\n\nBUG #1 — THE EMOTION SUPPRESSION MEMORY LEAK\nif emotion.detected() {\n    emotion.suppress() // \"Not now, I'm working\"\n    intellectualize(emotion) // \"I understand why I feel this way\"\n    // NOTE: emotion not actually deallocated\n    // Still consuming memory\n    // Will cause crash at 3am or during next argument\n}\n\nYou think you've handled the emotion because you UNDERSTOOD it. Understanding is not processing. It's like reading the error log without fixing the bug. The emotion stays in memory, leaking resources until it forces a crash — an outburst, a breakdown, insomnia, physical symptoms.\n\nBUG #2 — THE PROJECTION REDIRECT\nfunc evaluateCoworker(_ person: Person) -> Assessment {\n    // BUG: checking own shadow traits, not actual person\n    if self.shadow.contains(.anger) {\n        return .hostile // \"They're always so aggressive\"\n    }\n    // The anger is yours. You projected it.\n}\n\nEvery time someone \"triggers\" you disproportionately — that coworker who annoys you way more than they should, that personality type you can't stand — you're not seeing them clearly. You're seeing your own disowned trait reflected back at you. The brain literally can't tell the difference. Same neural pathways fire.\n\nBUG #3 — THE INFINITE LOOP (\"Why Does This Keep Happening?\")\nwhile true {\n    enterRelationship(type: .familiar)\n    repeatConflictPattern()\n    breakUp(reason: \"They were the problem\")\n    // No exit condition because pattern is unconscious\n    // Will loop until shadow code is reviewed\n}\n\nSame type of partner. Same argument at month 3. Same burnout cycle at every job. Same distance from your family. You change the inputs (new person, new company, new city) but the output is identical because the PROCESSING CODE hasn't changed.\n\nBUG #4 — THE FALSE OPTIMIZATION\nfunc optimizeLife() {\n    work.hours += 20 // \"I'll just work harder\"\n    gym.sessions += 3 // \"I'll optimize my body\"\n    productivity.apps += 5 // \"I need a better system\"\n    // Actual issue: unprocessed grief from 2019\n    // None of this addresses the root cause\n}\n\nEngineers love to optimize. But optimizing the wrong thing is worse than doing nothing. When the real issue is emotional — grief, fear, shame, unprocessed trauma — no amount of habit-tracking or productivity hacking will fix it. You're polishing the UI while the database is corrupted."),
                ],
                reflectionPrompt: "Which bug feels most familiar? Memory leak (suppressed emotions)? Projection redirect? Infinite loop? False optimization? Be honest — the one that makes you uncomfortable is probably yours."
            ),
            
            // ═══════════════════════════════════════════════════
            // LESSON 3: Where the Shadow Code Comes From
            // ═══════════════════════════════════════════════════
            AwakeningLesson(
                id: "joa_m7b_l3",
                number: 3,
                title: "Where the Shadow Code Comes From",
                subtitle: "The commits you don't remember making",
                emoji: "📜",
                sections: [
                    AwakeningSection(heading: "The Git History You Never Read", body: "Every piece of shadow code has a commit history. You just never looked at it. Let me show you the major commit sources.\n\nCOMMIT SOURCE 1 — Family (Ages 0-7)\nThis is your initial codebase. You didn't write it — it was written FOR you.\n\n• Dad never showed emotion → commit: suppress_vulnerability.swift\n• Mom's love was conditional on achievement → commit: self_worth_equals_performance.swift\n• Parents fought about money → commit: money_equals_danger.swift\n• Sibling got attention for being loud → commit: suppress_needs_be_invisible.swift\n\nThese commits happened before you could think critically. They went straight into production with no code review. And they're STILL running.\n\nCOMMIT SOURCE 2 — School (Ages 5-18)\n• \"Sit down and be quiet\" → commit: suppress_energy_creativity.swift\n• Bullied for being different → commit: conform_to_survive.swift\n• Praised only for grades → commit: value_equals_output.swift\n• Punished for questioning authority → commit: obey_dont_think.swift\n\n13 years of daily commits to your shadow repo. Every day, 8 hours a day, the system was programmed.\n\nCOMMIT SOURCE 3 — Culture (Always Running)\n• \"Real men don't cry\" → commit: masculinity_requires_numbness.swift\n• \"Success means sacrifice\" → commit: rest_is_weakness.swift\n• \"Don't air dirty laundry\" → commit: hide_problems.swift\n• \"Be grateful, others have it worse\" → commit: invalidate_own_pain.swift\n\nCOMMIT SOURCE 4 — Trauma (Timestamps Vary)\nThe big ones. The commits that got pushed directly to main with no PR, no review, no tests.\n\n• Betrayal → commit: trust_no_one.swift\n• Abandonment → commit: never_depend_on_anyone.swift\n• Humiliation → commit: never_be_vulnerable_again.swift\n• Loss → commit: dont_love_too_deeply.swift\n\nTrauma commits have the highest priority in the runtime. They override everything else. Your logical brain says \"this person is safe\" but the trauma commit fires first: DENIED. The amygdala doesn't care about your rational analysis. It has root access."),
                    AwakeningSection(heading: "Why Understanding + Knowing ≠ Fixed", body: "Here's where engineers get stuck. We think understanding the architecture IS the fix.\n\nIt's not.\n\nKnowing that suppress_vulnerability.swift exists in your codebase doesn't stop it from executing. You can read the source code all day. You can explain it to your therapist. You can draw a perfect diagram of your childhood dynamics.\n\nThe code is still running.\n\nThis is the critical distinction that took me forever to get:\n\nINTELLECTUAL UNDERSTANDING = Reading the error log\nEMOTIONAL PROCESSING = Actually fixing the bug\n\nYou have to FEEL the code execute, catch it in real-time, and consciously choose a different path. That's the refactor. That's the actual work.\n\nYou can't think your way out of a feeling. You can't architect your way out of grief. You can't optimize your way out of shame.\n\nYou have to FEEL it. Process it. Let it complete its execution cycle. Then — and only then — can you write the replacement code.\n\nFor an engineer, this is the hardest lesson. Our superpower (logic, analysis, systems thinking) is also our biggest shadow trap. We use it to AVOID the feeling while convincing ourselves we're \"working on it.\"\n\nReading about swimming is not swimming. Analyzing your emotions is not feeling them."),
                ],
                reflectionPrompt: "Can I identify one specific 'commit' from childhood that's still running in my adult life? What was the original context? Does it still serve me?"
            ),
            
            // ═══════════════════════════════════════════════════
            // LESSON 4: The Engineer's Debugging Protocol
            // ═══════════════════════════════════════════════════
            AwakeningLesson(
                id: "joa_m7b_l4",
                number: 4,
                title: "The Engineer's Debugging Protocol",
                subtitle: "6 steps. No crystals. Just root cause analysis.",
                emoji: "🔍",
                sections: [
                    AwakeningSection(heading: "Step 1: Set Up Logging (Daily System Scan)", body: "You can't debug what you don't log.\n\nEvery evening, 5 minutes. Three questions:\n\n1. What emotion did I feel but not express today?\n   (This catches the memory leak in real-time)\n\n2. Where did I judge someone disproportionately?\n   (This catches projection — your shadow reflected in others)\n\n3. What pattern repeated?\n   (This catches the infinite loops)\n\nWrite it down. Not in your head — externally. In a notes app, a journal, a spreadsheet. Data you don't persist is data you lose.\n\nDo this for 7 days before touching anything else. You're gathering baseline metrics. Don't try to fix. Just observe and log.\n\nYou'll be shocked how quickly patterns emerge. Same emotion. Same trigger. Same response. Over and over."),
                    AwakeningSection(heading: "Step 2: Breakpoint — Catch the Bug Mid-Execution", body: "When you feel a disproportionate emotional reaction — tight chest, jaw clenching, sudden defensiveness, urge to check your phone, snap at someone, shut down — that's the shadow code executing.\n\nSet a breakpoint.\n\n1. PAUSE. Don't react. Don't suppress. Don't intellectualize. Just stop.\n\n2. NAME IT + LOCATE IT.\n   \"Anger. In my jaw and fists.\"\n   \"Shame. In my chest and stomach.\"\n   \"Fear. Throat tight, shoulders up.\"\n   Naming the emotion with its body location engages the prefrontal cortex, which starts down-regulating the amygdala. This is neuroscience, not philosophy.\n\n3. RATE IT. Intensity 1-10. This gives you quantifiable data over time.\n\n4. HOLD FOR 90 SECONDS.\n   Stay with the sensation. Don't add a story (\"They shouldn't have said that\"). Don't suppress it (\"I'm fine\"). Just observe the raw data — the physical sensation in your body.\n\n   Why 90 seconds? Neuroanatomist Jill Bolte Taylor's research: the chemical lifespan of an emotion in the body is approximately 90 seconds. If it lasts longer, you're re-triggering it with narrative. The feeling is brief. Your story about the feeling is what makes it chronic.\n\n   Most engineers have never sat with an emotion for 90 seconds without analyzing it. This is the hardest and most important skill in the entire protocol."),
                    AwakeningSection(heading: "Step 3: Stack Trace — Talk to the Bug", body: "This is Jung's \"Active Imagination\" technique. It sounds weird. It works. Think of it as rubber duck debugging for your psyche.\n\n1. Sit quietly for 10 minutes. Close your eyes.\n\n2. Think of the pattern — the repeating emotion, the trigger, the person who bothered you.\n\n3. Let an image appear. It might be a character, a younger version of you, a symbolic figure, whatever your unconscious serves up. Don't force it. Don't judge it.\n\n4. Talk to it. Out loud or in writing.\n   - \"What do you need?\"\n   - \"What are you protecting me from?\"\n   - \"When did you first show up?\"\n   - \"What happens if I let you go?\"\n\n5. Write down the dialogue.\n\nThis isn't meditation. It's not mysticism. It's accessing the stack trace — going below the surface error to find the root function call that started the cascade.\n\nMany engineers report that the \"character\" is a younger version of themselves — a scared kid, an angry teenager, a version of them from a specific memory. That version wrote the shadow code. It had good reasons at the time. The code was a survival mechanism. It just hasn't been updated since.\n\nYou're not deleting old code. You're having a conversation with the developer who wrote it, understanding their constraints, and then writing a better version."),
                    AwakeningSection(heading: "Steps 4-6: Refactor, Express, Observe", body: "STEP 4: WRITE THE PATCH\nVisualize the old pattern as actual code. See it. Then write the replacement:\n\nOLD: if vulnerable_moment { shutdown(); isolate(); work_harder(); }\nNEW: if vulnerable_moment { breathe(); name_feeling(); reach_out_to_trusted_person(); }\n\nRun the new code mentally 3 times. Visualize yourself in the trigger situation, executing the new behavior. This is cognitive rehearsal — used in CBT, military training, and elite athletics. Your brain can't fully distinguish vivid mental rehearsal from real experience. Same neural pathways fire.\n\nSTEP 5: EXTERNALIZE (Get it Out of RAM)\nShadow material that stays internal keeps executing as background processes. Get it OUT:\n\n• Draw the pattern as a system diagram or flowchart\n• Write the shadow's \"release notes\" — what it was trying to do, why it was built, what it cost\n• Move the energy through your body: walk fast, do pushups, box, shake, dance terribly in your room\n\nThe body stores what the mind suppresses. If you've ever felt inexplicably better after intense exercise, that's cached emotion being released from the physical system.\n\nSTEP 6: OBSERVER MODE (Meta-Cognition Upgrade)\nInstead of \"I AM angry\" → practice \"I NOTICE I'm experiencing anger.\"\n\nThis single shift is the difference between being inside the code and watching it execute from the IDE. You become the developer, not the runtime.\n\nResearch (Teasdale et al., MBCT studies): 8 weeks of this observer practice reduces rumination by 40-60%. Not mysticism. Controlled trials. Measurable outcomes.\n\nJung's most important line: \"Until you make the unconscious conscious, it will direct your life and you will call it fate.\"\n\nIn engineer terms: until you read your own source code, the legacy bugs will keep shipping to production and you'll keep blaming external factors."),
                ],
                reflectionPrompt: "Which of the 6 steps am I most resistant to? The logging? The 90-second hold? Talking to the pattern? That resistance IS the shadow protecting itself from review."
            ),
            
            // ═══════════════════════════════════════════════════
            // LESSON 5: The 30-Day Sprint
            // ═══════════════════════════════════════════════════
            AwakeningLesson(
                id: "joa_m7b_l5",
                number: 5,
                title: "The 30-Day Sprint",
                subtitle: "Track it like any other engineering project",
                emoji: "📊",
                sections: [
                    AwakeningSection(heading: "Sprint Setup", body: "You wouldn't ship a feature without a timeline, metrics, and review cycles. Same here.\n\nDAILY TRACKER — 7 columns:\n• Date\n• Trigger (what happened externally)\n• Shadow Pattern Detected (which loop — personal, interpersonal, ancestral, cultural, archetypal)\n• Intensity (1-10)\n• Technique Used (which step from the protocol)\n• New Behavior Tested (what you did differently)\n• Outcome Metrics: Mood (1-10), Productivity (1-10), Sleep (1-10), Relationship Friction (1-10)\n\nWEEK 1-2: OBSERVATION SPRINT\nJust log. Don't fix. Gather baseline data. You will feel WORSE during this phase. This is normal. When you start logging suppressed emotions, they surface. It's like turning on the debugger for the first time — suddenly you see all the warnings you've been ignoring.\n\nThis is called a \"healing crisis\" in psychology. I call it \"debugging overload.\" The system is exposing bugs faster than you can fix them. It's temporary. Push through Week 2.\n\nWEEK 3-4: TARGETED REFACTORING\nBy now you'll see the same 2-3 patterns firing repeatedly. Those are your targets. Apply Steps 3-6 specifically to these patterns.\n\nEND OF SPRINT: RETROSPECTIVE\nCompare Week 4 metrics to Week 1. Most people report measurable improvement in at least 2 of 4 outcome metrics. If you tracked honestly, the data speaks for itself."),
                    AwakeningSection(heading: "What Engineers Report After 30 Days", body: "Based on clinical outcomes (Jungian analysis, IFS therapy) and anecdotal reports from technical professionals:\n\nFEWER REPEATING BUGS\nThe same argument with your partner doesn't happen the third time because you caught the projection in Week 2 and refactored the trigger response.\n\nBETTER SYSTEM STABILITY\nEmotional regulation under pressure improves. Not because you suppress more effectively — because there's less suppressed material causing random crashes. Your emotional runtime has fewer background processes hogging resources.\n\nHIGHER OUTPUT QUALITY\nCreativity increases when cognitive resources aren't being consumed by emotional suppression. Multiple fMRI studies confirm: suppressed emotions literally reduce prefrontal cortex function. Free up that RAM and your problem-solving gets sharper.\n\nCLEANER INTERFACES\nLess projection means you see people more clearly. Less defensiveness means better collaboration. Less need for validation means better leadership. Your API with other humans gets cleaner.\n\nTHE UNEXPECTED BENEFIT\nMany engineers report that shadow work made them BETTER engineers. Not because of any mystical reason — because understanding your own operating system makes you better at understanding ALL systems. Pattern recognition sharpens. Empathy for users improves. Tolerance for ambiguity increases. The skills transfer."),
                    AwakeningSection(heading: "When to Escalate", body: "Risk management. Read this carefully.\n\nESCALATE TO A PROFESSIONAL WHEN:\n• Material surfaces linked to trauma (abuse, violence, major loss)\n• You experience prolonged inability to function (can't work, can't sleep, can't eat)\n• Suicidal ideation appears — even briefly\n• Dissociation occurs (feeling detached from reality, watching yourself from outside)\n• The 30-day sprint makes things significantly worse with no improvement by Week 3\n\nThis is the equivalent of calling a senior engineer when you hit a production-critical bug you can't solve alone. Not weakness. Wisdom.\n\nLook for: Licensed psychologists trained in Jungian analysis, Internal Family Systems (IFS), EMDR, or somatic experiencing. These modalities specifically work with shadow/unconscious material. Avoid anyone who just gives you coping strategies without going deeper — that's putting a try/catch around the bug instead of fixing it.\n\nNEVER use shadow insights as weapons against others. Understanding someone's patterns doesn't give you permission to \"diagnose\" them or exploit their vulnerabilities. That's weaponizing the tools. Don't be that developer.\n\nTHE BOTTOM LINE\nYou don't have to believe in anything. Not God, not chakras, not the astral plane, not karma, not the Bible. None of that is required.\n\nAll you have to do is this: look at your own source code. Read the commits you've been ignoring. Talk to the parts of yourself you've been suppressing. Feel what you've been intellectualizing. And measure the results.\n\nJung spent decades collecting data. Modern neuroscience validates the mechanisms. IFS research confirms the model.\n\nShadow integration is root-cause analysis applied to your own mental operating system. Run the experiment. Track the metrics. Let the data speak.\n\nYour most important codebase isn't the one at work. It's the one running you."),
                ],
                reflectionPrompt: "Am I willing to commit to 30 days of honest self-observation? If not — what's the resistance? And what is that resistance protecting?"
            ),
        ]
    )
}
