// LDModule1_JesusAcrossReligions.swift
// Module 1: Jesus Across World Religions
// Same figure. 8 traditions. 8 completely different readings.
// "Understanding how different faiths view Jesus doesn't just teach you about religion.
//  It shows you how radically different people can read the same figure
//  and walk away with completely different conclusions."
// ☀️ SunFlow: Reignited

import SwiftUI

extension LightAndDarknessCourse {
    
    static let module1_JesusAcrossReligions = AwakeningModule(
        id: "ld_m1",
        number: 1,
        title: "Jesus Across World Religions",
        subtitle: "Same figure. 8 traditions. 8 completely different readings.",
        emoji: "✝️",
        estimatedMinutes: 90,
        lessons: [
            
            // ═══════════════════════════════════════
            // LESSON 1: Why This Matters
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "ld_m1_l1",
                number: 1,
                title: "Why Study Multiple Views",
                subtitle: "The lens changes what you see",
                emoji: "🔍",
                sections: [
                    AwakeningSection(heading: "One Figure, Many Lenses", body: "Jesus of Nazareth might be the most interpreted human being in history. Over 2 billion Christians worship him as God incarnate. 1.8 billion Muslims honor him as one of the greatest prophets. Buddhists admire him as a compassionate teacher. Hindus see him as a guru, saint, or possible avatar. New Age thinkers call him an enlightened master who achieved \"Christ consciousness.\"\n\nSame person. Radically different conclusions.\n\nWhy does this matter for your awakening? Because it reveals something profound about how human consciousness works: we don't see reality directly. We see reality through our framework — our tradition, our conditioning, our inherited lens.\n\nChristians read Isaiah 53 and see Jesus predicted. Jews read the same passage and see the nation of Israel. Muslims read the Gospels and see a prophet whose message was later distorted. New Age thinkers read the same words and see a metaphor for ego death and spiritual rebirth.\n\nThis isn't about who's \"right.\" This is about recognizing that EVERY tradition — including yours — is a lens. And lenses both reveal and distort.\n\nThe goal of this module isn't to convert you to anything. It's to show you how the same figure looks completely different depending on which floor of the building you're standing on (remember the Planes module?). Once you see this pattern with Jesus, you'll start seeing it everywhere — in politics, in science, in your own relationships.\n\nThe person who can hold multiple lenses simultaneously without collapsing into any single one? That's someone who sees clearly. That's Aperture."),
                    AwakeningSection(heading: "Ground Rules", body: "Before we begin:\n\n1. RESPECT: Every tradition described here is someone's deepest truth. We present each view from WITHIN that tradition's own logic, not from outside looking in to criticize.\n\n2. OBJECTIVITY: We're not ranking these views. We're mapping them. Like the Comparison Matrix in Module 5 — different architects, same building.\n\n3. PRIMARY SOURCES: Every claim is traceable to that tradition's own scriptures or scholarly consensus. We're not strawmanning anyone.\n\n4. YOUR DISCERNMENT: After seeing all views, YOU decide what resonates. That's cognitive sovereignty. That's ERSS applied to religion itself.\n\n5. THE PATTERN: Pay attention to what's SHARED across all views, not just what's different. The shared elements are often the signal. The differences are often the noise of cultural conditioning.\n\nLet's begin."),
                ],
                reflectionPrompt: "What lens do I currently view Jesus through — and where did that lens come from? Family? Culture? Personal experience? Default assumption?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 2: Judaism & Islam
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "ld_m1_l2",
                number: 2,
                title: "Judaism & Islam",
                subtitle: "Teacher vs. prophet — two Abrahamic views",
                emoji: "📖",
                sections: [
                    AwakeningSection(heading: "Judaism: A Jewish Teacher, Not the Messiah", body: "In Judaism, Jesus is understood as a first-century Jewish teacher — not the promised Messiah and not divine.\n\nThe key: Judaism's messianic expectations are specific. The Messiah is a future descendant of David who brings visible, lasting peace, restores justice, and gathers the exiles of Israel. Since the world didn't enter that kind of peace in the first century, most Jewish communities don't see Jesus as having fulfilled the messianic job description.\n\nChristians often point to passages like Isaiah 53, Psalm 22, or Daniel 7 as predictions of Jesus. Jewish interpretation reads these texts differently — for example, seeing the \"suffering servant\" in Isaiah as the nation of Israel itself, or as a historical figure from that era.\n\nSo it's not about which verses exist. It's about how they're read. Same text. Different interpretive framework. Different conclusion.\n\nJesus doesn't appear in the Tanakh (Hebrew Bible) itself. References come later in some rabbinic writings, and they're complex, debated, and not central to Jewish faith or practice.\n\nThe heart of Judaism stays focused on: covenant life with God, worshiping the one God (the Shema in Deuteronomy 6:4), keeping Torah, and pursuing justice and mercy.\n\nModern Jewish opinions on Jesus range from skeptical to respectfully curious. Scholars like Martin Buber admired Jesus as a pious Jew. Amy-Jill Levine argues he fits within first-century Judaism's Pharisaic debates.\n\nThe takeaway: Judaism doesn't build its faith around Jesus because it doesn't identify him as Messiah or God. But it recognizes him as part of Jewish and world history."),
                    AwakeningSection(heading: "Islam: One of the Greatest Prophets — But Not Divine", body: "For Muslims, Jesus (known as Isa) is one of the greatest prophets — born of the Virgin Mary, honored with miracles performed by God's permission. The Quran speaks about him with deep respect. He heals, he teaches, he points people back to worshiping the one true God.\n\nIslam even calls Jesus the Messiah (al-Masih), though the meaning differs from Christian theology.\n\nThe main dividing line: divinity. Islam rejects the idea that Jesus is God or the Son of God in the Christian sense. It also rejects the Trinity. From an Islamic viewpoint, God (Allah) is absolutely one — no partners, no shared essence, no God in human form. This is called tawhid.\n\nAnother major difference: the crucifixion. The New Testament presents Jesus's death by crucifixion as a historical event. The Quran says Jesus was not killed or crucified in the way people thought, and that God raised him up (Quran 4:157). Muslims commonly understand this as God saving Jesus from that death.\n\nWhy this matters: In Islam, Jesus is not the final word. He's a signpost pointing forward. The final prophet is Muhammad, and Jesus's role supports that larger storyline.\n\nMany Muslims believe Jesus will return near the end of time to defeat deception and restore justice — not as a crucified savior to be worshiped, but as a servant of God completing his mission.\n\nJesus appears in 93 Quranic verses — more mentions than Muhammad. That's how deeply he's honored. But the framework is fundamentally different: a beloved prophet within a strictly monotheistic theology.\n\nPATTERN TO NOTICE: Both Judaism and Islam share strict monotheism. Both honor Jesus to varying degrees. Both reject the Trinity. Both redirect focus away from Jesus as divine center — Judaism toward Torah, Islam toward Muhammad as final prophet."),
                ],
                reflectionPrompt: "If I grew up in a Jewish or Muslim family, how might I naturally view Jesus? What does that tell me about how much of my worldview is inherited versus chosen?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 3: Buddhism & Hinduism
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "ld_m1_l3",
                number: 3,
                title: "Buddhism & Hinduism",
                subtitle: "Admirable teacher vs. possible avatar",
                emoji: "🕉️",
                sections: [
                    AwakeningSection(heading: "Buddhism: Compassionate Teacher, Not Central", body: "Buddhism isn't built around worshiping a creator God or trusting in a savior to remove sin. The core problem is suffering (dukkha), driven by craving and ignorance. The core solution is awakening — seeing reality clearly and living with compassion, mindfulness, and wisdom.\n\nJesus doesn't appear in Buddhist scriptures. You won't find him in the sutras as a doctrinal authority. But in the modern world, many Buddhists talk about Jesus with genuine respect.\n\nSome view him as a wise teacher. Others see parallels between Jesus's compassion and what Buddhism calls the bodhisattva ideal — someone who embodies self-giving love for others, delaying their own final liberation to serve.\n\nThe contrast becomes sharp when you compare claims. In the Gospels, Jesus speaks with unique authority, forgives sins, and calls people into relationship with God. Buddhism doesn't frame the human condition as guilt before God but as bondage to ignorance, healed through insight and practice.\n\nSo when Buddhists engage Jesus, it lands in admiration rather than worship. A moral example, a compassionate healer, an inspirational figure. He can be appreciated without being required.\n\nThe Dalai Lama's \"The Good Heart\" (1996) admires Jesus's compassion but notes doctrinal differences. Thich Nhat Hanh sees parallels in mindfulness practice.\n\nKey distinction: Buddhism's map of the problem and the cure is drawn in a completely different language. No creator God, no sin, no salvation through faith — awakening through direct insight."),
                    AwakeningSection(heading: "Hinduism: Many Paths, Many Views", body: "There isn't a single Hindu view of Jesus because Hinduism is diverse — more like a vast spiritual library than one defined creed.\n\nMany Hindus respect Jesus deeply, seeing him as a holy man, a teacher of love, or a powerful example of devotion (bhakti). Some interpret him through Hindu categories: guru, realized soul, or even avatar (divine incarnation, like Krishna or Rama).\n\nOthers fold Jesus into a \"many paths to God\" framework where he's one true revelation among many — valuable and real, but not exclusive.\n\nThis is where interpretations collide or blend. In the New Testament, Jesus makes strong identity claims and calls for trust and allegiance, especially in John's Gospel (\"I am the way, the truth, and the life\"). Classical Christian teaching centers on Jesus as uniquely God-with-us — not simply one spiritual master alongside others.\n\nAt the same time, Hindu devotional traditions (bhakti) can resonate deeply with Christian devotion — love, surrender, worship. Some Hindus find the Sermon on the Mount compelling. Some admire Jesus's compassion for the poor. Some even incorporate Jesus into personal devotion without formally becoming Christian.\n\nGandhi saw Jesus as a truth-seeker (satyagrahi). Ram Mohan Roy praised his ethical teachings. The variety is the key — two Hindus can talk about Jesus and mean very different things, both speaking sincerely from within their tradition's wide spectrum.\n\nPATTERN TO NOTICE: Both Buddhism and Hinduism can INCLUDE Jesus without placing him at the center. This inclusive approach contrasts with Christianity's exclusive claims. Neither approach is automatically \"right\" — they're different architectures for processing the same data point."),
                ],
                reflectionPrompt: "What's the difference between 'admiring' a teacher and 'worshiping' a divine figure? Where do I fall on that spectrum with the teachers I follow?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 4: Bahá'í, LDS, Jehovah's Witnesses
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "ld_m1_l4",
                number: 4,
                title: "Bahá'í, LDS & Jehovah's Witnesses",
                subtitle: "Progressive revelation, restoration, and the created son",
                emoji: "⭐",
                sections: [
                    AwakeningSection(heading: "Bahá'í: Manifestation of God in Progressive Revelation", body: "In the Bahá'í Faith, Jesus is honored as a \"Manifestation of God\" — a divine messenger who reveals God's will to humanity. Bahá'ís place Jesus in a line of major figures: Abraham, Moses, Krishna, Buddha, Zoroaster, Muhammad, and culminating with Bahá'u'lláh in the 19th century.\n\nJesus is not viewed as just a teacher, but also not as God incarnate in the Trinitarian sense. Instead, Bahá'í thought emphasizes progressive revelation — God sends messengers across history, each bringing guidance suited to their time, all pointing to the same ultimate God.\n\nBahá'ís revere the Gospels and accept many core elements of Jesus's story — his moral authority, his suffering, and the power of his message. But they interpret certain doctrines differently, especially resurrection (seen as spiritually real — the triumph of Jesus's cause — rather than primarily physical).\n\nThe \"return of Christ\" is understood as the appearance of a new messenger carrying the same divine authority — like a new sunrise, not the old sun coming back.\n\nThis view tries to preserve Jesus's greatness while building bridges between religions. Jesus remains central — one of history's brightest lights — but he's part of a larger ongoing story."),
                    AwakeningSection(heading: "Latter-day Saints: Divine Son, Expanded Scripture", body: "In the Church of Jesus Christ of Latter-day Saints (LDS), Jesus is the divine Son of God, the promised Messiah, and the savior of the world. They take the Bible seriously but also believe in additional scripture — the Book of Mormon presents Jesus appearing to people in the ancient Americas after his resurrection.\n\nTheir view of God differs from mainstream Christianity. The Father, the Son, and the Holy Ghost are three distinct beings perfectly united in purpose (the Godhead), rather than one God in three persons (the Trinity). Jesus is understood as pre-existent — he lived with the Father before being born on earth.\n\nSalvation strongly emphasizes Jesus's atoning work, focusing on both Gethsemane and the cross, followed by literal bodily resurrection. They also teach ongoing restoration of divine authority through modern prophets.\n\nJesus isn't peripheral — he's the absolute center. But the framework around him (God's nature, additional scripture, restoration) creates a distinct branch of the Christian family tree.\n\nJEHOVAH'S WITNESSES: THE CREATED SON\n\nJehovah's Witnesses place Jesus at the center of God's plan but understand his identity differently. Jesus is the Son of God, the Messiah, and the world's redeemer — but not God Almighty. Jehovah alone is the one true God, and Jesus is Jehovah's first and greatest creation.\n\nThey point to verses emphasizing Jesus's dependence on the Father: \"The Father is greater than I\" (John 14:28). Many identify Jesus's pre-human existence with Michael the Archangel.\n\nThe crucifixion matters deeply — described as death on a torture stake rather than a traditional cross. Jesus's sacrifice is a ransom making eternal life possible. They teach Jesus was resurrected as a powerful spirit creature, not in a human body of flesh.\n\nA distinctive part: They teach Christ began ruling invisibly as king in heaven in 1914 and that we are living in the last days. Their door-to-door preaching flows from that urgency.\n\nThey honor Jesus, follow him, and trust his sacrifice — but reserve worship exclusively for Jehovah.\n\nPATTERN: Even within Christianity, views of Jesus diverge dramatically. The Trinity isn't universally accepted. The nature of resurrection is debated. Additional scriptures create different narratives. Same starting point (the Gospels), multiple conclusions."),
                ],
                reflectionPrompt: "If groups that all claim to follow Jesus reach different conclusions about who he IS — what does that tell me about the reliability of any single interpretation?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 5: New Age & The Meta-Pattern
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "ld_m1_l5",
                number: 5,
                title: "New Age View & The Meta-Pattern",
                subtitle: "Christ consciousness and what all 8 views reveal together",
                emoji: "🌀",
                sections: [
                    AwakeningSection(heading: "New Age: Enlightened Master & Christ Consciousness", body: "New Age spirituality isn't one organized religion — it's a wide umbrella blending self-help, mysticism, metaphysics, and elements of many traditions. The view of Jesus varies, but patterns recur.\n\nMany describe Jesus as an enlightened master — someone who reached a high spiritual state and came to model what humans can become. Phrases like \"ascended master,\" \"way-shower,\" or \"teacher of unconditional love\" are common.\n\nInstead of focusing on Jesus dying for sin and rising again as the center of salvation history, New Age thought often treats those events as symbols: death representing ego death, resurrection representing spiritual awakening.\n\nThe key concept: Christ consciousness — the belief that \"the Christ\" is a universal spiritual energy or state of awareness, not uniquely tied to Jesus alone. Jesus embodied it clearly, but the goal is for YOU to awaken to that same inner divinity.\n\nThis differs sharply from how Jesus presents himself in the Gospels. The New Testament portrays him as someone who speaks with God's authority, calls for repentance, and claims a unique role. New Age readings soften those exclusive claims and reframe them as metaphorical or misinterpreted.\n\nThe center of gravity shifts: In Christianity, the spotlight stays on WHO Jesus is and what he did. In New Age spirituality, it shifts to what Jesus can teach you about your own inner potential. Less courtroom and covenant, more journey and awakening."),
                    AwakeningSection(heading: "The Meta-Pattern: What All 8 Views Reveal", body: "Now step back and look at ALL eight views together. What pattern emerges?\n\nWHAT THEY ALL SHARE:\n• Universal respect for Jesus's ethical teachings (love, compassion, justice)\n• Recognition of his historical significance\n• Acknowledgment that his life and message changed the world\n\nWHERE THEY DIVERGE:\n• Is he God? (Christianity yes, Islam/Judaism/JW no, others vary)\n• Is he the ONLY way? (Christianity often yes, Hinduism/Bahá'í/Buddhism no)\n• Did he physically die and rise? (Christianity yes, Islam no, JW spiritual only, Bahá'í spiritual)\n• Is his role unique or exemplary? (Christianity unique, New Age exemplary)\n\nTHE DEEPER PATTERN:\nEvery tradition takes the same historical data (a first-century Jewish teacher who was executed and whose followers claimed resurrection) and processes it through a completely different interpretive framework.\n\nJudaism: Doesn't meet messianic criteria.\nIslam: Great prophet, but not final, not divine.\nBuddhism: Admirable but not necessary.\nHinduism: One of many valid paths.\nBahá'í: One in a series of progressive revelations.\nLDS: Divine, with expanded scripture.\nJW: Created son, not God himself.\nNew Age: Symbol of universal consciousness.\nChristianity: God incarnate, unique savior.\n\nNine different conclusions from the same starting point.\n\nWhat does this tell you? That the LENS matters as much as the data. That inherited frameworks shape perception before conscious analysis begins. That the same reality looks completely different depending on which floor you're standing on.\n\nThis is exactly what the Planes of Existence module showed you — same building, different floor, different view. This is what ERSS teaches — every narrative is processed through existing priors.\n\nThe person who has studied ALL views? They can choose their position consciously rather than inheriting it unconsciously. They can hold respect for multiple perspectives without collapsing into relativism OR fundamentalism.\n\nThat's seeing clearly. That's knowing both sides."),
                ],
                reflectionPrompt: "After seeing all 8 views — has my own view of Jesus shifted, deepened, or been confirmed? What does my reaction tell me about my own framework?"
            ),
        ]
    )
}
