// JourneysOfAwakeningQuantumCognition.swift
// Module 11: Quantum Cognition — When Math Meets Consciousness
// Your brain doesn't run on classical logic. Neither does the universe.
// The math is lit. 🔥
// ☀️ SunFlow: Reignited

import SwiftUI

// MARK: - ═══════════════════════════════════════════════════
// MODULE 11: QUANTUM COGNITION & MENTAL FIRMWARE
// ═══════════════════════════════════════════════════════════

extension JourneysOfAwakeningCourse {
    
    static let module11_QuantumCognition = AwakeningModule(
        id: "joa_m11",
        number: 11,
        title: "Quantum Cognition",
        subtitle: "When math meets consciousness — and the math wins",
        emoji: "⚛️",
        estimatedMinutes: 65,
        lessons: [
            
            // ═══════════════════════════════════════
            // LESSON 1: Your Brain Isn't Classical
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m11_l1",
                number: 1,
                title: "Your Brain Isn't Classical",
                subtitle: "Why Boolean logic fails and quantum probability wins",
                emoji: "🎲",
                sections: [
                    AwakeningSection(heading: "The Shocking Discovery", body: "For decades, cognitive science assumed human thinking follows classical logic. Yes/no. True/false. If A then B. Boolean operators. Clean, predictable, computable.\n\nThere was just one problem: humans kept breaking the rules.\n\nPeople consistently violate classical probability in their judgments. They commit the conjunction fallacy (thinking two events together are MORE probable than either alone). Their decisions change depending on the ORDER questions are asked. They show interference effects — where considering option A changes the probability of choosing option B, even when A and B are logically independent.\n\nClassical probability theory can't explain this. For decades, these were called \"cognitive biases\" — bugs in human reasoning that evolution should have fixed.\n\nThen Busemeyer, Bruza, and others asked a radical question: what if human cognition isn't buggy? What if it's just not CLASSICAL?\n\nStudy: Busemeyer & Bruza (2012, 2nd ed. 2024) — Quantum Models of Cognition and Decision, Cambridge University Press.\n\nThey applied quantum probability theory — the same math that describes subatomic particles — to human judgment. And it fit. Better than any classical model.\n\nNot because the brain is a quantum computer (that's a different debate). But because the MATHEMATICAL STRUCTURE of quantum probability — superposition, interference, contextuality, non-commutativity — describes how human minds actually process uncertainty better than classical Boolean logic does."),
                    AwakeningSection(heading: "What This Means in Plain English", body: "SUPERPOSITION\nIn quantum physics, a particle can be in multiple states simultaneously until measured. In your mind: you can hold contradictory beliefs, feelings, and possibilities at the same time — and they're all \"real\" until a decision collapses them into one.\n\nEver felt simultaneously excited AND terrified about the same thing? That's not confusion. That's superposition. Both states are real. The \"measurement\" (decision or action) collapses them into one experience.\n\nINTERFERENCE\nIn quantum physics, probability waves can amplify or cancel each other. In your mind: thinking about one option genuinely changes the probability of choosing another. Creativity often works this way — two unrelated ideas interfere constructively and produce an insight that neither could have produced alone.\n\nThis is why brainstorming works. Why meditation produces creative breakthroughs. Why the best ideas come in the shower. You're allowing interference between mental states that focused \"classical\" thinking keeps separate.\n\nNON-COMMUTATIVITY\nIn quantum physics, the order of measurements matters — measuring position then momentum gives different results than momentum then position. In your mind: the order in which you consider information changes your judgment.\n\nStudy: Order effects in surveys. Ask \"Is the president trustworthy?\" then \"Is the president competent?\" versus the reverse order. You get statistically different results. Classical probability says order shouldn't matter. Quantum probability predicts exactly this.\n\nCONTEXTUALITY\nIn quantum physics, the outcome depends on how you measure. In your mind: the same information produces different judgments depending on context. Your shadow material creates context — unprocessed fear changes how you interpret neutral data.\n\nThis is why two people can look at the same evidence and reach opposite conclusions. They're measuring from different contexts. Their shadow priors are different."),
                    AwakeningSection(heading: "Shadow Work in Quantum Terms", body: "Now map this to everything we've covered:\n\nSHADOW = ENTANGLED STATES\nYour conscious traits and your shadow traits are entangled. They're not separate — they're complementary aspects of the same system. You can't fully describe one without the other.\n\nJung's Thinking/Feeling dichotomy? In quantum terms, these are non-commuting observables. You can't precisely measure both simultaneously. When Thinking dominates (engineering mode), Feeling goes into superposition (shadow). It's still there — it's just not being measured. And unmeasured states still influence the system.\n\nPROJECTION = CONTEXT-DEPENDENT COLLAPSE\nWhen you project your shadow onto someone else, you're performing a measurement in the wrong basis. You think you're measuring THEM, but your measurement apparatus (your perception) is calibrated to your own shadow. The outcome tells you more about your instrument than about the thing you're measuring.\n\nINTEGRATION = UPDATING THE MEASUREMENT BASIS\nShadow work doesn't eliminate the entangled states. It changes how you measure. You develop the ability to observe both Thinking AND Feeling without one collapsing the other. In quantum terms: you expand your measurement basis to include more of the Hilbert space.\n\nSYNCHRONICITY = HIGH-INFORMATION SURPRISE\nIn Friston's free-energy framework: your brain flags events that have very low probability in your current model but very high significance. That's a synchronicity. It's your brain's pattern detection system saying: \"This data point doesn't fit your model. Update required.\"\n\nNo quantum mysticism needed. Just the mathematics of how complex systems process information under uncertainty."),
                ],
                reflectionPrompt: "Have I ever held contradictory feelings about the same situation? What if that's not confusion but superposition — and both states are real information?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 2: Predictive Coding
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m11_l2",
                number: 2,
                title: "Your Brain Is a Prediction Machine",
                subtitle: "Active inference, free energy, and why anxiety is a miscalibrated model",
                emoji: "📈",
                sections: [
                    AwakeningSection(heading: "The Free Energy Principle", body: "Karl Friston's Free Energy Principle (2010) might be the most important theory in neuroscience this century. It says:\n\nYour brain's primary job is to minimize prediction error.\n\nEvery moment, your brain generates a model of what SHOULD happen next — based on everything it's learned. Then it compares that prediction to what actually happens. The difference = prediction error.\n\nHigh prediction error = surprise = the brain mobilizes resources to deal with it.\nLow prediction error = everything is as expected = the brain can relax.\n\nThe brain minimizes prediction error in two ways:\n1. UPDATE THE MODEL (learning) — change your predictions to match reality\n2. CHANGE REALITY TO MATCH THE MODEL (action) — act on the world to make your predictions come true\n\nThis is called active inference. And it explains almost everything.\n\nANXIETY = chronically high prediction error. Your model keeps predicting threats that don't materialize, but instead of updating the model (\"maybe I'm safe\"), the brain doubles down on threat predictions.\n\nDEPRESSION = model that predicts nothing will work, so it stops generating actions. Low prediction error because it predicts nothing and gets nothing.\n\nSHADOW MATERIAL = high-precision priors (very confident predictions) that were written during trauma. They resist updating because the brain treats them as survival-critical. \"Never trust anyone\" was a reasonable prediction when written at age 8 after betrayal. At age 35, it's a miscalibrated prior generating chronic prediction error in every relationship."),
                    AwakeningSection(heading: "Meditation = Precision Recalibration", body: "Here's where it all connects.\n\nMeditation is NOT relaxation. It's not \"clearing your mind.\" It's precision recalibration of your predictive control system.\n\nStudy: Laukkonen & Slagter (2025) — Beautiful Loop Theory\nMeditation modulates the PRECISION of predictions at multiple levels of the processing hierarchy.\n\nFocused Attention meditation: Increases precision on selected signals (breath, body sensation) while decreasing precision on background noise (rumination, worry). You're training the brain to allocate prediction resources more efficiently.\n\nOpen Monitoring meditation: Reduces precision on ALL top-down predictions simultaneously. This allows the system to notice prediction errors it was previously ignoring — including shadow material that high-precision priors had been suppressing.\n\nThis is why meditation sometimes surfaces uncomfortable emotions. You're reducing the precision of the suppression model. The stuff you've been hiding from yourself becomes visible because the filter weakens.\n\nPSYCHEDELICS do the same thing, more dramatically. Psilocybin and DMT massively reduce the precision of top-down predictions (Carhart-Harris et al., REBUS model). The entire predictive hierarchy loosens. Everything that was suppressed surfaces at once. That's why psychedelic experiences can be profoundly therapeutic — and profoundly overwhelming.\n\nMeditation does it gradually. Psychedelics do it all at once. Same mechanism. Different dosage.\n\nStudy: Mount Sinai / IONS (2025)\n8 weeks of meditation practice shows deep-brain changes in memory and emotion regulation circuits — not just cortical surface changes. The recalibration reaches the subcortical systems where shadow material is stored.\n\nTHE DARK NIGHT REVISITED\nThe Dark Night of the Soul? In predictive coding terms: a catastrophic prediction error cascade. Your entire self-model — your identity, your beliefs, your life narrative — generates massive prediction errors because the old model is dissolving and the new one isn't online yet.\n\nYou're between firmware versions. The old OS is uninstalling. The new one is still downloading. Everything crashes.\n\nBut on the other side: a model with lower chronic prediction error. Less anxiety. Less projection. More accurate perception. Better calibrated priors.\n\nSt. John of the Cross called it passive purification. Friston would call it radical model update under high free energy. Same night."),
                ],
                reflectionPrompt: "Where in my life am I experiencing chronic prediction error — situations where I keep expecting something that doesn't match reality? What outdated prior might be causing it?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 3: Advanced Frameworks
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m11_l3",
                number: 3,
                title: "Advanced Frameworks",
                subtitle: "Open systems, multi-qubit models, and hybrid architectures",
                emoji: "🏛️",
                sections: [
                    AwakeningSection(heading: "Open Quantum Systems — Your Mind Isn't Isolated", body: "Basic quantum cognition uses pure states and simple measurements. But your mind doesn't operate in a vacuum. It's constantly interacting with environment — your body, other people, culture, sensory input.\n\nAdvanced models treat the mind as an OPEN quantum system.\n\nDENSITY OPERATORS\nInstead of pure states (single vectors), your mental state is a density matrix — a statistical mixture of multiple states simultaneously. The shadow isn't a single hidden thing. It's a mixed state with high entropy (disorder) on the repressed subspaces.\n\nIntegration = reducing entropy. Moving from a mixed, disordered state toward a more coherent, pure state. Not by eliminating complexity — by organizing it.\n\nLINDBLAD DYNAMICS\nThe Lindblad master equation describes how open quantum systems evolve while interacting with environment. Applied to cognition:\n\n• The Hamiltonian (H) = your internal dynamics (decision drives, personality structure)\n• The Lindblad operators (L) = decoherence from external noise (stress, habits, social pressure)\n\nShadow persistence is a non-Markovian effect — the system has LONG MEMORY. Trauma from 20 years ago still affects today's decisions because the memory kernel doesn't decay classically. It's stored in a way that resists normal updating.\n\nThis is exactly what clinicians observe: trauma responses don't fade with time alone. They require active reconsolidation (targeted measurement + update)."),
                    AwakeningSection(heading: "Multi-Qubit Personality Models", body: "This is where it gets genuinely elegant.\n\nBlutner & Hochnadel (2009), extended through 2025-2026:\n\nModel personality as a two-qubit system:\n• Qubit 1: Rational/Irrational axis (Thinking vs. Intuition)\n• Qubit 2: Judging/Perceiving axis (Structure vs. Flow)\n\nThe Shadow operates as a bit-flip (X-gate) on the complementary qubit. If your dominant mode is Thinking (rational, analytical), your shadow is Feeling (emotional, relational). The X-gate flips you into the shadow state — that's what happens during emotional overwhelm. The engineer who suddenly can't think clearly and is flooded with feeling? Bit-flip. The shadow qubit activated.\n\nPersonality types emerge from the tensor product of these qubits + entanglement between them. The 16 personality types (MBTI-like) map to states in a 4-dimensional Hilbert space.\n\nAdvanced extension: 4-qubit models capturing Shadow + Anima/Animus + Persona + Self as tensor networks. Each Jungian structure occupies a subspace. Integration = increasing entanglement between subspaces until they function as a coherent whole.\n\nJung's mandala — the symbol of the Self — is literally a visual representation of a high-dimensional coherent state. He drew what the math describes.\n\nHYBRID MODELS (2025 Breakthroughs)\nLaukkonen & Slagter + Friston integrations model the mind as a hierarchical quantum-like inference engine:\n\n• Top levels: classical Bayesian processing (rational decisions, logical planning)\n• Lower levels: quantum-like superposition for ambiguous perception and emotional processing\n\nMeditation = precision control that reduces free energy by collapsing unneeded superpositions at the right level. You're not \"clearing your mind.\" You're optimizing which superpositions to maintain (creative possibilities) and which to collapse (anxious rumination).\n\nEvidence: Quantum-like neural network models outperform classical RNNs on bistable perception tasks and order-effect predictions (Helland, 2026 benchmarks).\n\nThe math works. The predictions hold. The models outperform classical alternatives.\n\nScience and the universe really do work together. And the math really is lit."),
                ],
                reflectionPrompt: "If my personality has a 'complementary qubit' (shadow), what function am I dominant in — and what's the flip side I've been suppressing?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 4: Firmware Protocols 2.0
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m11_l4",
                number: 4,
                title: "Firmware Updates 2.0",
                subtitle: "Advanced protocols with quantum parameters",
                emoji: "⬆️",
                sections: [
                    AwakeningSection(heading: "Building on the Foundation", body: "Module 9 gave you four evidence-based meditation protocols. This lesson adds quantum-informed parameters for engineers and scientists who want the next layer.\n\nAll protocols below build on the foundation. Don't skip to these — complete the 8-week basic program first.\n\nPROTOCOL A: Quantum Active Imagination (10-15 min)\n1. PREPARE STATE: Relax. Note your current dominant mental mode (Thinking? Feeling? Planning? Worrying?). This is your current state vector.\n2. INTRODUCE SUPERPOSITION: Allow the complementary shadow image to arise WITHOUT collapsing it. If you're in Thinking mode, let Feeling show up. If you're in Control mode, let Surrender show up. Hold both.\n3. APPLY UNITARY ROTATION: Dialogue with the shadow state. \"What do you need?\" This is a controlled rotation in Hilbert space — not eliminating either state but finding the angle that integrates both.\n4. MEASURE: Record the outcome. Test the integrated insight in a real decision this week.\n\nMetric: Pre/post coherence score (1-10). How unified do you feel before vs. after?\n\nPROTOCOL B: Non-Markovian Memory Sweep (15 min)\nTarget: Ancestral and inherited patterns that persist across time.\n1. Body scan with temporal awareness — notice sensations and ask \"When did this pattern start?\"\n2. Follow the sensation backward. Your body stores temporal markers.\n3. Apply Lindblad-like decoherence: observe the old pattern without re-triggering. Neutral labeling only.\n4. Track intensity reduction across sessions.\n\nMetric: Trigger intensity score session over session. Should decrease non-linearly.\n\nPROTOCOL C: Entanglement Resolution (LKM + Tensor View)\nFor relationship patterns — interpersonal feedback loops.\n1. Visualize yourself and the other person as entangled qubits.\n2. Notice where your states are correlated — their anger triggers your shutdown, your criticism triggers their withdrawal.\n3. Apply controlled-NOT mentally: \"May you be safe.\" This flips the complementary state. Instead of reactivity → compassion. Instead of judgment → curiosity.\n4. Track relationship friction incidents.\n\nMetric: Weekly friction count + subjective connection score.\n\nPROTOCOL D: Hyper-Precision Meditation (20 min, Advanced)\n1. Open monitoring with explicit attention to prediction-error STRENGTH.\n2. Notice which thoughts have high precision (feel very \"true\" and urgent) vs. low precision (passing, light).\n3. Practice down-weighting high-precision shadow priors. That VERY URGENT feeling that \"something is wrong\"? Notice its precision. Ask: is this current data or old firmware?\n4. This directly implements Laukkonen's hyper-precision model.\n\nMetric: HRV (heart rate variability) if you have a tracker. Or simple breath-hold tolerance as a proxy for autonomic coherence. Both increase with practice."),
                    AwakeningSection(heading: "The Full Stack", body: "Let's zoom out and see what we've built across the science track:\n\nMODULE 7: Shadow Integration — What the shadow is, 5 feedback loops, 6-step protocol\nMODULE 8: Shadow for Engineers — Code metaphors, debugging workflow, 30-day sprint\nMODULE 9: Neuroscience of Awakening — DMN/SN/CEN, meditation = recalibration, dark night in the brain\nMODULE 10: Jung Through Brain Science — Every concept mapped to fMRI studies with citations\nMODULE 11: Quantum Cognition — Predictive coding, quantum probability, advanced firmware protocols\n\nFive modules. Zero mysticism. Every claim backed by peer-reviewed studies. Every protocol testable and measurable.\n\nBut here's the thing I need to say:\n\nThe science track and the spiritual track describe the same reality.\n\nRumi and Friston. St. John of the Cross and Willoughby Britton. The Upanishads and Panksepp. Jung and fMRI. They're all pointing at the same process.\n\nEgo dissolves → DMN downregulates.\nDark Night → catastrophic prediction error cascade.\nUnity Consciousness → triple network integration.\nKarma → feedback loops with non-Markovian memory.\nEnlightenment → optimal coherent state with minimal prediction error.\n\nYou don't have to choose between science and spirit. They're the same signal measured by different instruments.\n\nOne uses equations. The other uses poetry.\nBoth are accurate.\nNeither is complete alone.\n\nThat's the real lesson of this entire course. Not that one tradition has the answer. Not that one methodology is supreme. But that reality is multi-layered — and the more measurement systems you use, the clearer the picture becomes.\n\nScience and the universe work together.\nThe math is lit.\nAnd so are you. 🔥"),
                ],
                reflectionPrompt: "After going through both the spiritual and scientific tracks — which resonated more? And what does that preference tell me about my own cognitive style and potential blind spots?"
            ),
        ]
    )
}
