// JourneysOfAwakeningNeuroscienceModule.swift
// Module 9: The Neuroscience of Awakening
// "This is not woo-woo. Step right up — you'll see."
// Every mystical concept mapped to brain science. With citations.
// Science and the universe work together. The math is lit. 🔥
// ☀️ SunFlow: Reignited

import SwiftUI

// MARK: - ═══════════════════════════════════════════════════
// MODULE 9: NEUROSCIENCE OF AWAKENING
// ═══════════════════════════════════════════════════════════

extension JourneysOfAwakeningCourse {
    
    static let module9_Neuroscience = AwakeningModule(
        id: "joa_m9",
        number: 9,
        title: "The Neuroscience of Awakening",
        subtitle: "Not woo-woo. Step right up — you'll see.",
        emoji: "🧪",
        estimatedMinutes: 70,
        lessons: [
            
            // ═══════════════════════════════════════
            // LESSON 1: Same Process, Different Lab
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m9_l1",
                number: 1,
                title: "Same Process, Different Lab",
                subtitle: "What mystics described, neuroscience now measures",
                emoji: "🔬",
                sections: [
                    AwakeningSection(heading: "The Big Reveal", body: "Here's something that will either excite you or annoy you:\n\nEvery single concept in this course — shadow, ego death, unity consciousness, kundalini, dark night, planes of existence — has a measurable correlate in modern neuroscience.\n\nThe mystics described the experience. The scientists measured the mechanism. They're looking at the same elephant from different angles.\n\nRumi said: \"You are not a drop in the ocean. You are the entire ocean in a drop.\"\n\nA neuroscientist would say: \"During advanced meditation, the default mode network — the brain's self-referencing circuit — downregulates, and the boundary between self-representation and world-representation dissolves, producing a subjective experience of unity.\"\n\nSame thing. One is poetry. One is an fMRI readout. Both are accurate.\n\nThis module maps every key awakening concept to peer-reviewed brain science. Not to \"prove\" mysticism right — but to show that these aren't competing worldviews. They're complementary measurement systems describing the same reality.\n\nIf you're a skeptic: good. Skepticism is healthy. But dismiss the data at your own loss.\nIf you're spiritual: good. This will deepen your understanding of what's actually happening in your nervous system during the experiences you've had.\n\nEither way — citations included. Check them yourself."),
                    AwakeningSection(heading: "Three Brain Networks You Need to Know", body: "Before we map anything, you need to understand three brain networks. These are the key players in every awakening phenomenon.\n\nTHE DEFAULT MODE NETWORK (DMN)\nThe \"Me\" circuit. Active when you're thinking about yourself — replaying the past, planning the future, maintaining your sense of identity. It's the neural basis of ego.\n\nWhen the DMN is hyperactive: rumination, anxiety, depression, rigid self-concept. The Sleepwalker stage — endlessly thinking about \"me, me, me\" without awareness.\n\nWhen the DMN quiets: ego dissolution, present-moment awareness, flow states, mystical experiences. The Unity Consciousness stage.\n\nStudy: Brewer et al. (2011) — Experienced meditators show significantly reduced DMN activity during meditation, correlating with reduced self-referential thinking.\n\nTHE SALIENCE NETWORK (SN)\nThe \"What Matters\" circuit. Decides what deserves attention. Tags prediction errors — things that don't match your model of reality.\n\nOveractive SN + Shadow material = anxiety, hypervigilance, projection (everything feels like a threat because your model is full of unprocessed fear).\n\nBalanced SN = accurate threat detection, appropriate emotional response, synchronicity recognition (noticing meaningful patterns without paranoia).\n\nTHE CENTRAL EXECUTIVE NETWORK (CEN)\nThe \"Focus\" circuit. Directed attention, problem-solving, integration of information across brain regions.\n\nStrong CEN = good emotional regulation, clear decision-making, integration of unconscious material.\n\nThe goal of every contemplative practice across history — meditation, prayer, contemplation, shadow work — is the same neurologically: quiet the DMN, balance the SN, strengthen the CEN. Different traditions. Same neural target."),
                ],
                reflectionPrompt: "Which network feels most dominant in my daily life — the 'Me' circuit (DMN), the 'What's Threatening' circuit (SN), or the 'Focus' circuit (CEN)? What does that tell me?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 2: Shadow = Brain Science
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m9_l2",
                number: 2,
                title: "Shadow Work Under the fMRI",
                subtitle: "Projection, suppression, and the amygdala",
                emoji: "🧠",
                sections: [
                    AwakeningSection(heading: "The Shadow Is Measurable", body: "Jung described the Shadow in 1912. He couldn't prove it existed in the brain. Now we can.\n\nSHADOW = IMPLICIT MEMORY + AMYGDALA-PREFRONTAL MISMATCH\n\nWhen you suppress an emotion — anger, grief, fear, shame — it doesn't disappear. It gets stored in subcortical networks: the amygdala (threat detection), basal ganglia (habit loops), and insula (body sensation).\n\nStudy: Ochsner & Gross (2005) — Suppressed emotions INCREASE amygdala reactivity while REDUCING prefrontal cortex regulation. Translation: the more you suppress, the more reactive your threat detection becomes AND the less your rational brain can manage it.\n\nStudy: Etkin et al. (2015) — Chronic emotional suppression shows measurable amygdala hyperactivity on fMRI. The shadow isn't metaphorical. It's a pattern of neural firing that persists and strengthens over time.\n\nThis is why engineers who \"don't do emotions\" are often the most emotionally reactive when triggered. The suppression didn't eliminate the emotion — it amplified it while removing conscious access to it."),
                    AwakeningSection(heading: "Projection = False Positive Threat Detection", body: "Jung said projection is seeing your own disowned traits in other people. Neuroscience says: your brain is running a faulty threat model.\n\nThe brain is a prediction machine (Friston's Predictive Coding, 2010). It constantly generates top-down predictions about what will happen next and compares them to incoming sensory data. When there's a mismatch — a prediction error — the brain flags it for attention.\n\nShadow material creates mismatched priors. If you suppressed anger at age 7, your brain's model says \"anger = danger.\" Now, at 35, anyone who shows even mild assertiveness triggers a prediction error → amygdala fires → you perceive THREAT where none exists.\n\nThat's projection. It's not a spiritual concept. It's a Bayesian inference error caused by outdated training data.\n\nStudy: Internal Family Systems (IFS) research (Schwartz & Sweezy, 2019) shows that \"exiled\" emotional parts have measurable autonomic signatures — changes in heart rate variability and skin conductance. Shadow parts are real subsystems with real physiological markers.\n\nPRACTICAL IMPLICATION\nThe 90-second exposure technique from Module 7? Here's why it works neurologically: when you feel the emotion without adding a narrative, you allow the amygdala response to complete its cycle (approximately 90 seconds for the neurochemical cascade). The prefrontal cortex re-engages. The prediction model updates. The false positive gets corrected.\n\nJung called it integration. Neuroscience calls it memory reconsolidation. Same process."),
                    AwakeningSection(heading: "Archetypes = Evolved Neural Hardware", body: "Jung's archetypes — Hero, Shadow, Anima/Animus, Self, Trickster — were always his most controversial claim. Universal patterns in the \"collective unconscious\"? Sounds like mysticism.\n\nExcept evolutionary neuropsychology found them.\n\nStudy: Panksepp's Affective Neuroscience — Identified 7 primary emotional systems (SEEKING, RAGE, FEAR, LUST, CARE, PANIC/GRIEF, PLAY) conserved across ALL mammals. These aren't learned. They're hard-wired subcortical circuits. They operate below conscious awareness. They organize behavior across species.\n\nThese map directly to Jungian archetypes:\n• SEEKING system → Hero archetype (drive to explore, achieve)\n• RAGE system → Shadow (suppressed aggression)\n• CARE system → Great Mother archetype (nurturing, bonding)\n• FEAR/PANIC → Abandoned Child archetype\n\nStudy: Knox (2003) reframed archetypes as early attachment schemas wired into orbitofrontal and cingulate circuits. Your brain comes pre-loaded with templates for how to relate to the world — just like an operating system comes with default drivers.\n\nStudy: Cross-cultural fMRI (Whalen et al.) shows universal facial expression recognition activates conserved neural networks regardless of culture. The hardware is the same. The software (culture) varies.\n\nJung was describing evolutionary firmware. He just didn't have the vocabulary for it yet."),
                ],
                reflectionPrompt: "If projection is a Bayesian inference error caused by outdated training data — what 'training data' from my past might be generating false positives in my current life?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 3: Meditation = Neuroscience
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m9_l3",
                number: 3,
                title: "What Meditation Actually Does",
                subtitle: "fMRI, EEG, and why monks have thicker brains",
                emoji: "📡",
                sections: [
                    AwakeningSection(heading: "It's Not Relaxation. It's Precision Recalibration.", body: "\"Just relax and clear your mind.\" That's the worst description of meditation ever written. Here's what's actually happening:\n\nMeditation is targeted recalibration of your brain's predictive control system. Different techniques produce different, specific, measurable neural changes.\n\nFOCUSED ATTENTION MEDITATION (Shamatha, Centering Prayer, Dhikr)\nNeural effect: Strengthens prefrontal-parietal attention networks. Increases frontal theta and gamma synchrony.\nWhat it does: Improves your ability to direct attention. Reduces mind-wandering. Strengthens the CEN.\nStudy: Lutz et al. (2004) — Buddhist monks with 10,000+ hours show gamma oscillations 800% stronger than novices. Not percentages. Eight hundred percent.\n\nOPEN MONITORING MEDITATION (Vipassana, Zazen, Centering Prayer advanced)\nNeural effect: Reduces DMN hyperactivity. Balances DMN-SN-CEN coupling.\nWhat it does: You observe thoughts and emotions without reacting. This is literally training your brain to decouple the \"Me\" circuit from the \"React\" circuit.\nStudy: Brewer et al. (2011) — Experienced meditators show reduced activity in the posterior cingulate cortex (key DMN hub) even at REST. Their default state is less ego-identified.\n\nLOVING-KINDNESS MEDITATION (Metta, Sufi heart practices, Christian agape)\nNeural effect: Increases insula and anterior cingulate cortex activation (empathy circuits).\nWhat it does: Reduces projection. Increases accurate reading of others' emotional states. Decreases the \"false positive\" threat detection that shadow material creates.\nStudy: Weng et al. (2013) — Just 2 weeks of loving-kindness training showed measurable increases in altruistic behavior AND corresponding changes in neural empathy circuits.\n\nBODY SCAN / INTEROCEPTIVE AWARENESS (Yoga Nidra, somatic experiencing)\nNeural effect: Strengthens right insula connectivity — the brain's primary internal sensing organ.\nWhat it does: Improves your ability to detect your own body signals — the early warning system for shadow material. That \"tight chest\" or \"knot in stomach\" IS data. This practice trains you to read it.\nStudy: Farb et al. (2015) — Interoceptive meditation increases body-awareness accuracy and reduces alexithymia (inability to identify emotions)."),
                    AwakeningSection(heading: "Neuroplasticity: Your Brain Physically Changes", body: "This is the part that should blow your mind.\n\nMeditation doesn't just change brain ACTIVITY (temporary). It changes brain STRUCTURE (permanent).\n\nStudy: Hölzel et al. (2011) — 8 weeks of mindfulness meditation (MBSR) produced measurable increases in gray matter density in:\n• Hippocampus (learning, memory)\n• Temporo-parietal junction (empathy, perspective-taking)\n• Cerebellum (emotional regulation)\n\nAND measurable DECREASES in:\n• Amygdala gray matter density (threat reactivity)\n\n8 weeks. 30 minutes a day. Structural brain changes visible on MRI.\n\nStudy: Davidson & Lutz (2008) — Long-term meditators (10,000+ hours) show permanently thicker prefrontal cortex, stronger connectivity between emotional and rational brain regions, and faster recovery from emotional triggers.\n\nThis is what every tradition described as \"purification\" or \"refinement\" or \"ascension through the planes.\" The brain is literally rebuilding itself — reinforcing integration pathways, reducing threat reactivity, strengthening the circuits that allow you to hold multiple perspectives simultaneously.\n\nJung called it individuation. The Buddhists called it vipassana. The alchemists called it the Great Work. The neuroscientists call it experience-dependent neuroplasticity.\n\nSame process. Now we can photograph it."),
                    AwakeningSection(heading: "The Dark Night — In the Brain", body: "Remember Stage 5? The Dark Night of the Soul — when everything falls apart, identity dissolves, and meaning collapses?\n\nHere's what's happening neurologically:\n\nThe DMN (your \"Me\" circuit) is undergoing a major reorganization. The old self-model — built from family conditioning, cultural programming, ego defenses — is being dismantled. But the new, integrated model isn't online yet.\n\nYou're between operating systems. The old OS is uninstalling. The new one hasn't finished installing. The screen is black.\n\nStudy: Willoughby Britton's Dark Night Project (Brown University) has documented meditation-related \"adverse effects\" that parallel the Dark Night: depersonalization, anxiety, loss of meaning, emotional flooding, sense of ego dissolution. Her research shows these are not signs of failure — they're signs of deep neural reorganization.\n\nThe meditators who push through report exactly what the mystics describe: emergence on the other side with reduced DMN reactivity, increased CEN integration, and greater emotional flexibility.\n\nSt. John of the Cross described it as \"passive purification by God.\" Neuroscience describes it as \"DMN dissolution during intensive contemplative practice leading to network re-integration.\"\n\nPoetry and data. Same night. Same dawn."),
                ],
                reflectionPrompt: "If 8 weeks of 30-minute daily practice can physically change brain structure — what's my real reason for not starting? Is that reason a fact or a shadow?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 4: Synchronicity & Pattern Recognition
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m9_l4",
                number: 4,
                title: "Synchronicity Is Not Magic",
                subtitle: "Bayesian surprise, pattern detection, and why coincidences mean something",
                emoji: "🎯",
                sections: [
                    AwakeningSection(heading: "Jung's Most Controversial Idea — With Math", body: "Synchronicity — meaningful coincidence without causal connection — was Jung's wildest claim. He developed it with Nobel physicist Wolfgang Pauli. Most scientists dismissed it.\n\nThen predictive coding theory came along.\n\nFriston's Free Energy Principle (2010): Your brain is constantly running a predictive model. It generates expectations and compares them to reality. When something happens that has very low probability in your model but very high personal significance — that's a synchronicity.\n\nIn Bayesian terms: a synchronicity is a high-information, low-probability event that your brain's pattern detection system flags as meaningful.\n\nYour brain isn't making it up. It's doing exactly what it's designed to do — detect patterns and assign significance to improbable correlations. The question isn't whether synchronicities are \"real.\" The question is whether the patterns your brain detects are noise or signal.\n\nStudy: Anterior cingulate cortex and insula activation during \"meaningful coincidence detection\" mirrors the neural signature of insight moments (the \"aha!\" experience). Your brain processes synchronicities the same way it processes creative breakthroughs."),
                    AwakeningSection(heading: "Why Synchronicities Increase During Awakening", body: "People in active awakening (Stages 3-5) consistently report increased synchronicities. Skeptics say it's confirmation bias. The brain science offers a more interesting explanation.\n\nDuring intensive inner work — meditation, shadow processing, dark night — your brain's prediction model is being rebuilt. Old priors are dissolving. The DMN is quieting. The SN (salience network) is recalibrating.\n\nWhen the old model loosens its grip, your pattern detection becomes more sensitive. You notice connections your rigid old model would have filtered out. Not because the coincidences weren't happening before — but because your attention was locked into a narrower model.\n\nIt's like removing a spam filter that was blocking real emails. The emails were always there. You just couldn't see them.\n\nStudy: Alpha-gamma coupling research shows that states of relaxed alertness (alpha waves) combined with focused binding (gamma waves) produce peak pattern detection. This is exactly the brain state that meditation cultivates.\n\nJung and Pauli hypothesized that mind and matter share a common ordering principle (unus mundus). Modern complexity science (Atmanspacher & Fuchs, 2014) models this as lawful correlations emerging from shared contextual variables — no quantum mysticism required, just the mathematics of complex systems.\n\nWhether synchronicities are \"just\" your brain being a really good pattern detector, or whether they reflect something deeper about the structure of reality — the practical advice is the same: pay attention to them. They're high-value data points. Log them. Look for patterns across patterns. Test the hypotheses they suggest.\n\nYour brain is trying to tell you something. The question is whether you're listening."),
                ],
                reflectionPrompt: "Have I ever dismissed a meaningful coincidence as 'just random'? What if I started logging synchronicities like data points — would patterns emerge?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 5: The Protocols
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m9_l5",
                number: 5,
                title: "Evidence-Based Protocols",
                subtitle: "4 practices backed by studies. 8 weeks. Measurable results.",
                emoji: "📋",
                sections: [
                    AwakeningSection(heading: "Protocol 1: Focused Attention (10 min/day)", body: "WHAT: Sit. Pick an anchor — breath sensation at nostrils, heartbeat, or a neutral sound. Hold attention there. When mind wanders, note \"wandering\" and return. That's it.\n\nWHY IT WORKS: Each \"return\" strengthens the prefrontal-parietal attention network. It's a bicep curl for your CEN. The wandering isn't failure — it's the rep.\n\nNEURAL TARGET: Increased frontal theta + gamma synchrony. Stronger top-down prediction control.\n\nMETRIC: Count \"returns\" per session. Track over weeks. Lower returns = more stable attentional model.\n\nSHADOW LINK: Trains non-reactivity. When a shadow trigger fires, this is the muscle that lets you PAUSE instead of react.\n\nSTUDY: Lutz et al. (2004) — Gamma oscillations in trained practitioners. Jha et al. (2007) — 8 weeks of FA training improves attentional performance on standardized tests."),
                    AwakeningSection(heading: "Protocol 2: Open Monitoring (10 min/day)", body: "WHAT: Sit. Don't focus on anything specific. Notice whatever arises — thoughts, sensations, emotions, sounds — without labeling them good or bad. Just observe.\n\nThe advanced version: become aware of awareness itself. \"I notice I am noticing.\"\n\nWHY IT WORKS: Decouples the DMN from the SN. Your \"Me\" circuit stops hijacking your \"What Matters\" circuit. You start seeing reality more clearly because your self-narrative isn't coloring everything.\n\nNEURAL TARGET: Reduced DMN hyperactivity. Balanced DMN-SN-CEN coupling.\n\nMETRIC: Emotional volatility score. Rate your emotional reactivity each morning (1-10). Track trend.\n\nSHADOW LINK: Allows suppressed material to surface without triggering the old suppress-or-react cycle. You see the shadow arising and just... watch it. That's integration.\n\nSTUDY: Brewer et al. (2011) — Reduced posterior cingulate activity even at REST. Your baseline state becomes less ego-dominated."),
                    AwakeningSection(heading: "Protocol 3: Loving-Kindness (10 min, 3x/week)", body: "WHAT: Silently repeat phrases while holding someone in mind:\n\"May I be safe. May I be happy. May I be healthy. May I live with ease.\"\nStart with yourself. Then someone you love. Then a neutral person. Then someone difficult.\n\nWHY IT WORKS: Directly strengthens the empathy circuits (insula, anterior cingulate) that projection degrades. Reduces the amygdala's false-positive rate.\n\nNEURAL TARGET: Increased insula + ACC activation. Reduced amygdala reactivity to social stimuli.\n\nMETRIC: Relationship friction incidents per week. Track honestly.\n\nSHADOW LINK: The \"difficult person\" step is where projection gets healed. By generating genuine good-will toward someone who triggers you, you're updating the faulty Bayesian prior that says \"they are a threat.\"\n\nSTUDY: Weng et al. (2013) — 2 weeks produced measurable behavioral AND neural changes. Klimecki et al. (2014) — Compassion training reverses empathic distress patterns."),
                    AwakeningSection(heading: "Protocol 4: Body Scan (15 min, 2x/week)", body: "WHAT: Lie down or sit. Slowly move attention from toes to head, noticing any sensation — warmth, tingling, tightness, numbness, nothing. Don't judge. Just note.\n\nWHY IT WORKS: Strengthens the insula — your brain's internal sensor. The insula is where \"gut feelings\" become conscious data. Shadow material often manifests as body sensation (tight jaw = suppressed anger, churning stomach = anxiety, heavy chest = grief) BEFORE it reaches conscious awareness.\n\nNEURAL TARGET: Right insula connectivity. Interoceptive accuracy.\n\nMETRIC: Interoceptive accuracy. Test: can you count your heartbeats for 30 seconds without touching your pulse? Accuracy improves with practice.\n\nSHADOW LINK: Your body is storing what your mind is suppressing. This practice reads the data your conscious mind has been ignoring.\n\nSTUDY: Farb et al. (2015) — Increased body-awareness accuracy and reduced alexithymia (inability to identify emotions). Hölzel et al. (2011) — Structural changes in interoceptive regions after 8 weeks MBSR.\n\nTHE 8-WEEK PLAN:\nWeeks 1-2: Protocol 1 (Focused Attention) daily, 10 min\nWeeks 3-4: Add Protocol 2 (Open Monitoring), alternate days\nWeeks 5-6: Add Protocol 3 (Loving-Kindness) 3x/week + Protocol 4 (Body Scan) 2x/week\nWeeks 7-8: Mix all four. Track all metrics. Compare to baseline.\n\nExpected outcomes (from meta-analyses):\n• 25-45% reduction in rumination\n• 15-30% faster emotional recovery from triggers\n• Measurable increase in gray matter density in key integration areas\n• Improved decision-making under uncertainty\n\nThese aren't promises. They're statistical averages from controlled trials with thousands of participants. Run the experiment on yourself and measure."),
                ],
                reflectionPrompt: "Which protocol addresses my biggest current challenge — attention (FA), reactivity (OM), relationships (LKM), or body awareness (Body Scan)? Start there."
            ),
        ]
    )
}
