// JourneysOfAwakeningERSS.swift
// Module 12: Engineer Reality Scoring System (ERSS)
// High Clarity Capstone — Hakai-Level Psyop Detection
// "See Clearly. Think Clearly. Choose Freely."
// Turn discernment into a repeatable protocol.
// ☀️ SunFlow: Reignited

import SwiftUI

// MARK: - ═══════════════════════════════════════════════════
// MODULE 12: ERSS — ENGINEER REALITY SCORING SYSTEM
// ═══════════════════════════════════════════════════════════

extension JourneysOfAwakeningCourse {
    
    static let module12_ERSS = AwakeningModule(
        id: "joa_m12",
        number: 12,
        title: "Reality Scoring System (ERSS)",
        subtitle: "Detect engineered narratives. Score them. Choose freely.",
        emoji: "🎯",
        estimatedMinutes: 90,
        lessons: [
            
            // ═══════════════════════════════════════
            // LESSON 1: Why You Need This
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m12_l1",
                number: 1,
                title: "Why You Need a Scoring System",
                subtitle: "Your attention is the most valuable resource on Earth",
                emoji: "⚠️",
                sections: [
                    AwakeningSection(heading: "The Problem", body: "Every day, billions of dollars are spent engineering what you believe.\n\nNot informing you. ENGINEERING your beliefs. There's a difference.\n\nInformation says: \"Here are the facts. Draw your own conclusion.\"\nEngineered narrative says: \"Here's what to feel, who to blame, and what to do — and if you question it, you're the problem.\"\n\nEdward Bernays — Sigmund Freud's nephew — wrote the playbook in 1928. His book \"Propaganda\" literally opens with: \"The conscious and intelligent manipulation of the organized habits and opinions of the masses is an important element in democratic society.\"\n\nHe wasn't hiding it. He was bragging.\n\nSince then, the tools have gotten exponentially more sophisticated. Social media algorithms, 24/7 news cycles, synthetic media, astroturfed movements, controlled opposition — the manipulation stack in 2026 makes Bernays look like a kid with crayons.\n\nAnd your brain? Your brain is running the same hardware it had 200,000 years ago. Tribal wiring. Threat detection. Authority deference. Emotional override. Every single vulnerability that kept your ancestors alive on the savanna is now being exploited to control what you think, buy, vote for, and fear.\n\nYou can't fix this with willpower. You can't fix it by \"being smarter.\" You need a SYSTEM."),
                    AwakeningSection(heading: "What ERSS Is", body: "The Engineer Reality Scoring System is a structured, repeatable protocol for scoring the manipulation likelihood of ANY narrative — news story, policy announcement, social media trend, historical event, advertisement, or future scenario.\n\nIt uses 8 weighted indicators scored 0-12.5 each, producing a total score from 0-100.\n\n0-25: Low manipulation risk. Probably organic information.\n26-50: Moderate. Worth cross-checking independently.\n51-75: High. Probable psyop element. Apply deeper analysis.\n76-100: Engineered reality. High-confidence manipulation. Pause ALL action.\n\nThis isn't conspiracy thinking. It's the opposite. Conspiracy thinking is pattern-matching without rigor — seeing manipulation everywhere based on feelings. ERSS is rigorous, scored, and testable. It forces you to show your work.\n\nIf something scores low, accept it. If it scores high, investigate further. If you can't score it cleanly, that itself is data — the narrative may be deliberately ambiguous to resist analysis.\n\nThe goal isn't paranoia. The goal is SOVEREIGNTY. Reclaiming your attention, your emotions, and your decisions from systems designed to hijack them.\n\nStudies on structured checklist-based misinformation detection (Pennycook & Rand meta-analyses; MIT Media Lab) show they outperform gut intuition by 35-60%. Structure beats instinct when the game is rigged."),
                ],
                reflectionPrompt: "When was the last time I felt a strong emotional reaction to a news story — and later discovered the story was incomplete, misleading, or engineered? What did that cost me?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 2: The 8 Indicators
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m12_l2",
                number: 2,
                title: "The 8 Indicators",
                subtitle: "Score each 0-12.5. Total = manipulation likelihood.",
                emoji: "📊",
                sections: [
                    AwakeningSection(heading: "Indicator 1: Focus Hijack (0-12.5)", body: "WHAT TO LOOK FOR:\nRepetition, shocking visuals, disproportionate airtime, \"breaking news\" loops, algorithmic amplification.\n\nThe first move in any psyop is capturing attention. If every channel, every feed, every conversation is dominated by ONE story — ask why. Reality is complex. When it suddenly simplifies to a single narrative, someone is controlling the lens.\n\nSCORING:\n0 = Balanced, proportional coverage across multiple stories\n3 = Slightly elevated attention but organic (genuine major event)\n6 = Repetitive looping with emotional hooks\n9 = 24/7 saturation with identical framing across outlets\n12.5 = Total attention capture + active suppression of competing stories\n\nSHADOW CHECK: Is YOUR attention being hijacked because the story triggers a personal fear? Focus hijack works by exploiting existing prediction errors. If you're already anxious about X, a story about X captures you faster than someone who isn't."),
                    AwakeningSection(heading: "Indicator 2: Authority Inversion (0-12.5)", body: "WHAT TO LOOK FOR:\nExperts speaking outside their domain, manufactured consensus, tone shifts from informing to commanding, credential-waving without evidence, \"trust the science\" from non-scientists.\n\nLegitimate authority says: \"Here's what we found, here's our methodology, here are the limitations, draw your own conclusion.\"\n\nInverted authority says: \"We're the experts. Don't question us. If you disagree, you're dangerous.\"\n\nThe difference is transparency vs. demand for compliance.\n\nSCORING:\n0 = Domain-specific experts with transparent methodology and acknowledged uncertainty\n3 = Mild credential-leverage but evidence provided\n6 = Experts speaking outside domain OR consensus manufactured by repetition\n9 = Active silencing of credentialed dissenters + emotional authority appeals\n12.5 = Full authority inversion: questioning = heresy, compliance = virtue\n\nQUANTUM CHECK: Authority creates context. Your judgment about the SAME evidence changes depending on who presents it. That's contextuality. If removing the expert's name changes your assessment of the data — you're measuring the authority, not the evidence."),
                    AwakeningSection(heading: "Indicators 3-4: Tribal Polarization & Emotion Override", body: "INDICATOR 3: TRIBAL POLARIZATION (0-12.5)\n\nWHAT TO LOOK FOR:\nUs-vs-them language, identity labels (\"patriots vs. traitors,\" \"science believers vs. deniers\"), in-group signaling, shaming for questioning, social exclusion threats.\n\nHumans are wired for tribal belonging. We NEED groups. That wiring is 200,000 years old. Every psyop exploits it by creating artificial tribes and making you afraid of being expelled from yours.\n\nSCORING:\n0 = Neutral language, issue-focused, no identity attachment\n3 = Mild in-group preference but no demonization\n6 = Clear us/them framing with emotional charge\n9 = Active dehumanization of out-group + social punishment for dissent\n12.5 = Full tribal warfare narrative: loyalty = survival, questioning = betrayal\n\nUNITY CHECK: Does this narrative DIVIDE or UNITE? Every engineered narrative benefits from division. United people are ungovernable. Divided people are controllable. If the story makes you hate a group of humans — that's the tell.\n\n---\n\nINDICATOR 4: EMOTION OVERRIDE (0-12.5)\n\nWHAT TO LOOK FOR:\nFear without evidence, hope without substance, outrage without context, urgency without justification, scarcity pressure (\"act now or lose everything\").\n\nEmotions are data. They're valid. But when a narrative LEADS with emotion and provides evidence only as afterthought (or not at all) — that's emotional scripting.\n\nThe amygdala processes threats 5x faster than the prefrontal cortex processes logic. Every psyop is designed to hit the amygdala before the cortex has time to evaluate.\n\nSCORING:\n0 = Data-first presentation, emotions arise naturally from facts\n3 = Some emotional framing but facts available\n6 = Emotion leads, evidence trails behind\n9 = Pure emotional scripting with minimal verifiable data\n12.5 = Deliberate fear/outrage manufacturing + scarcity pressure + \"don't think, act now\"\n\nSHADOW CHECK: Which specific emotion is being triggered? If it's fear — what shadow material does it activate? Your personal fear signature is your vulnerability. Know it, and you become harder to hijack."),
                    AwakeningSection(heading: "Indicators 5-6: Novelty/Timing & Context Shift", body: "INDICATOR 5: NOVELTY & TIMING EXPLOITATION (0-12.5)\n\nWHAT TO LOOK FOR:\nSudden \"breaking\" events perfectly timed to distract from something else. New crisis erupting the day a damaging report drops. Pattern of convenient coincidences.\n\nThe news cycle has a memory of about 72 hours. Anything that falls outside that window effectively disappears. Timing is the most underrated manipulation tool.\n\nSCORING:\n0 = Organic timeline, no suspicious correlation with other events\n3 = Mild timing convenience but likely coincidental\n6 = Suspicious timing that warrants investigation\n9 = Clear distraction pattern: new crisis perfectly buries previous story\n12.5 = Manufactured event with precision timing + coordinated rollout across platforms\n\nPREDICTIVE CODING CHECK: Your brain's model expects \"breaking news\" to be important. That expectation is exploitable. High-novelty events generate massive prediction errors, flooding your system with attention and emotion — perfect conditions for slipping something past your rational defenses.\n\n---\n\nINDICATOR 6: CONTEXT BOUNDARY SHIFT (0-12.5)\n\nWHAT TO LOOK FOR:\n\"Emergency\" powers that normalize extreme measures, temporary rules that become permanent, gradual expansion of acceptable control, rapid compliance pressure (\"we don't have time to debate this\").\n\nThe phrase to watch for: \"Never let a crisis go to waste.\" — Rahm Emanuel\n\nEvery engineered crisis is an opportunity to shift the boundary of what's considered normal. Once shifted, it rarely shifts back.\n\nSCORING:\n0 = Consistent rules, transparent process, proportional response\n3 = Minor boundary adjustment with clear sunset clause\n6 = Significant shift framed as \"temporary\" with vague timeline\n9 = Permanent power expansion using emergency justification + social pressure to comply\n12.5 = Complete context rewrite: old normal erased, questioning the new normal = dangerous"),
                    AwakeningSection(heading: "Indicators 7-8: Follow-the-Money & Frame Analysis", body: "INDICATOR 7: FOLLOW-THE-MONEY & BENEFICIARY MAPPING (0-12.5)\n\nWHAT TO LOOK FOR:\nFunding trails, lobbying connections, industry gain from the narrative, stock movements around events, who profits from the proposed \"solution.\"\n\nThis is the most concrete indicator. Emotions can be debated. Money can be tracked.\n\nSCORING:\n0 = Transparent funding, no conflicts of interest, broad public benefit\n3 = Minor conflicts but disclosed\n6 = Undisclosed conflicts + clear financial beneficiaries\n9 = Massive profit concentration + active concealment of financial connections\n12.5 = Entire narrative exists to funnel resources to specific beneficiaries + evidence of pay-to-play\n\nACTION: Always ask \"Who benefits financially from me believing this?\" If you can't identify the beneficiary, dig deeper. If you find the beneficiary and they funded the narrative — score accordingly.\n\n---\n\nINDICATOR 8: FRAME & LOGICAL FALLACY CLUSTER (0-12.5)\n\nWHAT TO LOOK FOR:\nMicro-agreements (\"We can all agree that...\"), hero/villain archetypes (\"brave whistleblower vs. corrupt institution\" or reverse), and logical fallacies:\n\n1. Appeal to Emotion — \"Think of the children!\"\n2. Straw Man — Misrepresenting the opposing view to make it easier to attack\n3. Bandwagon — \"Everyone agrees\" / \"The science is settled\"\n4. False Dilemma — \"You're either with us or against us\"\n5. Ad Hominem — Attack the person, not the argument\n6. Appeal to Authority — \"Dr. Expert says so\" (without evidence)\n7. Slippery Slope — \"If we allow X, soon Y and Z will happen\"\n8. Hasty Generalization — \"One example proves the rule\"\n9. Red Herring — Introducing irrelevant topic to distract\n10. False Equivalence — Equating two very different things\n\nSCORING:\n0 = Clean logic, transparent framing, no fallacies detected\n3 = 1 fallacy, likely unintentional\n6 = 2-3 fallacies with clear narrative framing\n9 = 4+ fallacies + hero/villain archetype + micro-agreements\n12.5 = Full narrative engineering: layered fallacies + identity hooks + archetype casting + deliberate frame control"),
                ],
                reflectionPrompt: "Pick any current headline. Can I score it across all 8 indicators? Where does it land on the 0-100 scale? Did the exercise change how I feel about the story?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 3: How to Run ERSS
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m12_l3",
                number: 3,
                title: "Running the Protocol",
                subtitle: "5-10 minutes. Root-cause analysis for reality.",
                emoji: "🔍",
                sections: [
                    AwakeningSection(heading: "Step-by-Step", body: "Run this like a root-cause analysis. Same discipline. Same rigor.\n\nSTEP 1: CAPTURE RAW INPUT (30 seconds)\nSave the headline, screenshot, video clip, or event description. Note the date, source, and platform. Don't analyze yet — just capture.\n\nSTEP 2: RUN ERSS SCORING (5-10 minutes)\nGo through each indicator. Score 0-12.5. Write brief evidence for each score. Don't overthink — first-pass scoring is usually accurate.\n\nSTEP 3: APPLY GROUNDED FILTERS (2 minutes)\nShadow Check: \"Is this triggering my personal projection? Am I seeing this as threatening because of MY shadow, or because it genuinely IS threatening?\"\nQuantum Check: \"Is this context-dependent? Would I score it differently if the source were different?\"\nPredictive Coding Check: \"What prediction error is being amplified? Is my model actually wrong, or is someone exploiting my model's vulnerabilities?\"\n\nSTEP 4: CROSS-VERIFY (5 minutes)\nFind 3 independent sources. Not 3 outlets running the same wire story — 3 genuinely independent perspectives. Map the beneficiaries.\n\nSTEP 5: DECIDE & LOG\nFour options:\n□ Accept as data — Score is low. Information appears organic. File it.\n□ Cross-verify — Score is moderate. Need more data before forming opinion.\n□ Pause & Observe — Score is high. Do NOT act on this emotionally. Watch how the narrative develops over 72 hours.\n□ Counter with facts — Score is very high. You've identified likely manipulation. Share your analysis (not your outrage) with others.\n\nSTEP 6: ITERATE\nAdd every scored event to your personal dataset. Over time, you'll see meta-patterns: which outlets score high consistently, which types of events are most engineered, which of YOUR vulnerabilities get exploited most often.\n\nThat's ERSS. It takes 10 minutes. It turns you from passive consumer into active systems debugger.\n\nThe most powerful version is when you score something you AGREE with. That's where the real work happens. Scoring narratives you disagree with is easy — your bias does the work. Scoring narratives that validate your existing beliefs? That takes integrity."),
                    AwakeningSection(heading: "The Unity Test", body: "After scoring, always ask one final question:\n\n\"Does accepting this narrative increase division or unity?\"\n\nThis isn't naive. This is the deepest pattern recognition in the entire course.\n\nEvery engineered narrative benefits from division. EVERY one. Because divided people are controllable. United people are not.\n\nIf a story makes you hate a group of humans — any group — that's the biggest red flag of all. Not because the group is innocent. Not because criticism is wrong. But because hate is the most exploitable emotion humans produce, and every power structure in history has used it to maintain control.\n\nThe billionaire doesn't fear the liberal OR the conservative. The billionaire fears the day they stop fighting each other and look up.\n\nThe politician doesn't fear the left OR the right. The politician fears the day both sides realize they're being played by the same game.\n\nTribal division is the oldest psyop on Earth. And it still works because it hijacks wiring that's 200,000 years old.\n\nERSS helps you see through it. Not by making you suspicious of everything — but by giving you a structured way to separate signal from noise, information from manipulation, and genuine threat from manufactured fear.\n\nSee clearly. Think clearly. Choose freely. That's Aperture."),
                ],
                reflectionPrompt: "Am I willing to score a narrative I currently believe in? What would happen to my worldview if it scored above 50?"
            ),
            
            // ═══════════════════════════════════════
            // LESSON 4: Calibration Examples
            // ═══════════════════════════════════════
            AwakeningLesson(
                id: "joa_m12_l4",
                number: 4,
                title: "Calibration & Practice",
                subtitle: "Score real events. Build your database.",
                emoji: "📈",
                sections: [
                    AwakeningSection(heading: "Historical Calibration", body: "To trust the system, you need to calibrate it against known events. Here are examples where the historical record is well-documented:\n\nEXAMPLE: GULF OF TONKIN INCIDENT (1964)\nNarrative: \"North Vietnam attacked US destroyers unprovoked.\"\nResult: Used to justify massive escalation of Vietnam War.\nHistorical truth: Declassified NSA documents (2005) confirmed the second attack never happened.\n\nERSS Score:\n1. Focus Hijack: 11/12.5 — Wall-to-wall coverage, no competing narratives\n2. Authority Inversion: 10/12.5 — President and military speaking definitively without evidence\n3. Tribal Polarization: 9/12.5 — \"Support our troops\" = loyalty test\n4. Emotion Override: 12/12.5 — Pure fear + patriotic rage\n5. Novelty & Timing: 11/12.5 — Perfectly timed for Congressional authorization vote\n6. Context Boundary Shift: 12/12.5 — Tonkin Resolution gave president near-unlimited war power\n7. Follow-the-Money: 10/12.5 — Defense contractors, military-industrial complex\n8. Frame & Fallacies: 10/12.5 — False dilemma, appeal to patriotism, hasty generalization\n\nTOTAL: 85/100 — Engineered Reality\nConfirmed by declassified documents 41 years later.\n\nEXAMPLE: IRAQ WMD (2002-2003)\nNarrative: \"Iraq has weapons of mass destruction. We must act.\"\nResult: Full-scale invasion. Hundreds of thousands of casualties.\nHistorical truth: No WMDs found. Intelligence was cherry-picked and fabricated.\n\nERSS Score: 92/100\nEvery single indicator scored 9+ . The playbook was textbook.\n\nThese aren't conspiracy theories. These are declassified, acknowledged, documented historical events. ERSS would have flagged both in real-time if anyone had been using it."),
                    AwakeningSection(heading: "Practice Framework", body: "YOUR ASSIGNMENT:\n\nPick three events — one from each category:\n\n1. HISTORICAL: Choose any well-documented event you already know the outcome of. Score it. See if ERSS matches the historical record.\n\n2. CURRENT: Choose a narrative that's active RIGHT NOW. Score it. Save the report. Check back in 30-90 days to see how it develops.\n\n3. PERSONAL: Choose a belief you hold strongly. Not a news event — a personal conviction. Score the narrative that gave you that belief. This is the hardest and most valuable exercise.\n\nTips for honest scoring:\n• Score BEFORE you research. Your first-pass intuition, structured through the 8 indicators, is usually more accurate than post-research rationalization.\n• If you can't score an indicator, note \"insufficient data\" — that itself is informative.\n• Pay special attention to Indicator 3 (Tribal Polarization). If a narrative makes you feel contempt for a group of humans, add 2 points to every indicator as a bias correction.\n• Keep a running log. Over weeks, your pattern recognition will sharpen dramatically.\n\nThe goal is not to score everything as a psyop. The goal is to score ACCURATELY. Some events are organic. Some crises are real. Some authorities are legitimate. The system helps you tell the difference — with data instead of paranoia.\n\nCAUTION:\nERSS is probabilistic, not infallible. A high score means \"investigate further,\" not \"this is definitely fake.\" A low score means \"probably organic,\" not \"definitely true.\"\n\nNever weaponize ERSS against individuals. It's designed for narratives and systems, not people. Using it to \"score\" a person's trustworthiness is a misuse of the tool.\n\nAnd if your ERSS scores are consistently above 80 for EVERYTHING you encounter — you may be in a paranoia spiral. That's your shadow projecting threat onto every input. Step back. Ground. Apply the shadow protocol from Module 7. Then return to scoring with fresh eyes."),
                ],
                reflectionPrompt: "After scoring my first real event — did the process change how I relate to the narrative? Did I feel more sovereign over my own attention and emotions?"
            ),
        ]
    )
}
