// JourneysOfAwakeningPlanesModule.swift
// Unit 6: The Planes of Existence — Layers of Reality Across Global Traditions
// "It took me forever to understand the planes... hopefully this will help someone."
// Plain language. No gatekeeping. Every tradition's map, side by side.
// ☀️ SunFlow: Reignited

import SwiftUI

// MARK: - ═══════════════════════════════════════════════════
// MODULE 6: PLANES OF EXISTENCE
// ═══════════════════════════════════════════════════════════

extension JourneysOfAwakeningCourse {
    
    static let module6_Planes = AwakeningModule(
        id: "joa_m6",
        number: 6,
        title: "The Planes of Existence",
        subtitle: "Eight layers of reality — every tradition's map",
        emoji: "🏗️",
        estimatedMinutes: 75,
        lessons: [
            // LESSON 1: What Are Planes? (No Jargon Intro)
            AwakeningLesson(
                id: "joa_m6_l1",
                number: 1,
                title: "What Are \"Planes\"?",
                subtitle: "Think of reality like a building with floors",
                emoji: "🏢",
                sections: [
                    AwakeningSection(heading: "Drop the Mystical Language", body: "Let's be real — \"planes of existence\" sounds like something from a fantasy novel. It scared me off for months. So let me explain it the way I wish someone had explained it to me.\n\nThink of reality like a building with floors.\n\nYou live on the ground floor. That's the physical world — your body, your job, your commute, your bills. Everything you can touch, see, hear. This is the floor most people spend their entire lives on without ever knowing there are other floors.\n\nBut every major tradition on Earth — Hindu, Buddhist, Christian, Islamic, Jewish, Egyptian, Greek — says the building has more floors. And they all drew maps of those floors. Different names, different numbers of levels, but the same basic idea: reality has layers, and most humans only experience the densest one."),
                    AwakeningSection(heading: "Why Should I Care?", body: "Because you've probably already visited other floors without knowing it.\n\nEver had a dream so vivid it felt more real than waking life? That's a floor.\n\nEver had a gut feeling about someone that turned out to be exactly right — but you had no logical reason to know? That's information from another floor.\n\nEver been in deep meditation or flow state and felt like time stopped and you were connected to something massive? Another floor.\n\nEver had the \"Is this all there is?\" feeling while everything in your life was technically fine? That's your consciousness knocking on the ceiling, trying to get upstairs.\n\nThe planes aren't places you travel to like airports. They're states of awareness you can access. You're already in the building. You just haven't explored all the floors yet."),
                    AwakeningSection(heading: "Every Tradition Drew a Map", body: "Here's what's wild: civilizations that never contacted each other drew almost identical maps.\n\nHinduism describes 14 lokas (worlds/planes) — 7 above Earth, 7 below.\n\nTheosophy (Western esoteric tradition) maps 7 planes from physical to divine.\n\nKabbalah (Jewish mysticism) uses the Tree of Life — 10 sephirot representing levels from material to infinite.\n\nDante's Divine Comedy (Christian) describes concentric spheres from Earth through heavens to the Empyrean (pure light of God).\n\nBuddhism describes 31 planes of existence across desire, form, and formless realms.\n\nGnosticism describes ascending through Archonic spheres to reach the Pleroma (fullness, true reality).\n\nDifferent languages. Different centuries. Different continents. Same building.\n\nWe're going to walk through 8 key floors that appear across most of these maps. For each one, I'll tell you: what it is in plain English, what traditions call it, how you might have already experienced it, what it connects to in the stages of awakening, and what to watch out for."),
                ],
                reflectionPrompt: "Have I ever had an experience — a dream, a feeling, a moment of expanded awareness — that felt like it came from a different \"floor\" of reality? What happened?"
            ),
            
            // LESSON 2: Earthly + Etheric + Astral (The Three You Already Know)
            AwakeningLesson(
                id: "joa_m6_l2",
                number: 2,
                title: "Floors 1-3: Physical, Etheric, Astral",
                subtitle: "The three layers you've already experienced",
                emoji: "🌍",
                sections: [
                    AwakeningSection(heading: "Floor 1: The Physical Plane — Where You Are Now", body: "The ground floor. Atoms, gravity, time, space, cause and effect. Your body lives here. Your senses operate here. Every other floor is accessed FROM here.\n\nWhat traditions call it:\n• Hinduism: Maya (the illusion — not that it's fake, but that it's not the WHOLE picture)\n• Kabbalah: Malkuth (\"The Kingdom\" — starting point of the Tree of Life)\n• Gnosticism: The material world created by the Demiurge\n• Buddhism: Samsara (the cycle of birth, death, rebirth)\n\nWhy it matters: Every tradition says this floor is sacred BECAUSE it's where you do the actual work. You can't skip it. Enlightenment doesn't mean escaping Earth — it means being fully present here while aware of the other floors.\n\nThe trap: Thinking this is the ONLY floor. That's the Sleepwalker stage. You eat, work, scroll, sleep, repeat — never looking up.\n\nThe other trap: Wanting to escape to \"higher\" floors and neglecting your actual life. That's spiritual bypassing."),
                    AwakeningSection(heading: "Floor 2: The Etheric Plane — The Energy Layer", body: "Think of this as the WiFi network running through the building. You can't see it, but it connects everything and carries information.\n\nThis is the layer of life-force energy. Every living thing has an etheric body — an energy blueprint that mirrors the physical body.\n\nWhat traditions call it:\n• Hinduism: Prana (life energy flowing through nadis/channels)\n• Chinese tradition: Qi/Chi (flowing through meridians — this is what acupuncture maps)\n• Western esotericism: The etheric body or vital body\n• Reiki/energy healing: The biofield\n\nYou've felt it when:\n• Your hands tingled during meditation or intense emotion\n• You felt someone's \"vibe\" before they spoke\n• You walked into a room and immediately felt tension or peace\n• You had a kundalini-style energy surge — heat, electricity, buzzing\n\nModern parallels: Biofield research, bioelectromagnetics, heart-rate variability studies showing measurable electromagnetic fields around the body.\n\nWatch out for: Getting obsessed with \"energy\" without doing the psychological work. Your chakras being \"open\" doesn't help if you haven't processed your trauma."),
                    AwakeningSection(heading: "Floor 3: The Astral Plane — The Dream Layer", body: "This is where things get wild. The astral plane is the layer of emotions, dreams, visions, and imagination — but cranked up to 100.\n\nImagine the physical world has rules: gravity, solid objects, linear time. The astral has none of that. Thoughts create reality instantly. Your emotions literally shape the landscape. Time is nonlinear.\n\nWhat traditions call it:\n• Hinduism: Kama-loka (desire realm)\n• Theosophy: The astral body / emotional body\n• Christianity/Islam: Intermediate heavens and hells (visions of saints, purgatory-like realms)\n• Sufism: The imaginal realm (alam al-mithal)\n\nYou've been here when:\n• You had a dream so vivid it felt like an actual experience\n• You experienced sleep paralysis with presences in the room\n• A meditation produced full visual scenes, beings, or landscapes\n• A psychedelic experience dissolved physical reality into flowing imagery\n• You did astral projection (whether intentional or accidental)\n\nThe beauty: It's incredibly creative, symbolic, and meaningful. Many insights and artistic inspirations come from here.\n\nThe trap: It's also where desires, fears, and unresolved emotions get amplified. Traditions warn about \"astral glamours\" — getting seduced by visions, entities, or powers and mistaking them for enlightenment. It's not enlightenment. It's floor 3. There are 5 more floors above you.\n\nModern parallel: Lucid dreaming, hypnagogic states, DMT experiences, Jung's active imagination."),
                ],
                reflectionPrompt: "Which of these three floors feels most familiar from my own experience? Physical (grounded, sensory), Etheric (energy, intuition), or Astral (dreams, visions, imagination)?"
            ),
            
            // LESSON 3: Mental + Causal (The Deep Floors)
            AwakeningLesson(
                id: "joa_m6_l3",
                number: 3,
                title: "Floors 4-5: Mental & Causal",
                subtitle: "Where thought becomes reality and the soul remembers",
                emoji: "🧠",
                sections: [
                    AwakeningSection(heading: "Floor 4: The Mental Plane — Where Ideas Are Alive", body: "Okay, this is where it gets harder to explain because we're beyond anything the five senses can process. Bear with me.\n\nThe mental plane is the realm of pure thought — but not the chattering monkey-mind thoughts you have during your commute. These are thoughts as living things. Ideas that exist independently of any individual thinker. Blueprints. Archetypes. Universal patterns.\n\nThink of it this way: on the physical plane, you see a tree. On the astral plane, you feel the tree's beauty or fear its shadow. On the mental plane, you perceive the IDEA of \"tree\" — the universal pattern that every tree on Earth is an expression of.\n\nPlato called these \"Forms\" or \"Ideas\" — the perfect templates that physical reality is a shadow of. He wasn't being poetic. He was describing the mental plane.\n\nWhat traditions call it:\n• Theosophy: Lower mental (concrete thought) and Higher mental (abstract, archetypal)\n• Hermeticism: The realm of the Akashic Records (cosmic memory/database)\n• Vedanta: Manas (mind) and Buddhi (higher intellect)\n• Kabbalah: Briah (the world of creation)\n\nYou've touched it when:\n• A solution to a problem appeared fully formed — not through logic but through sudden knowing\n• You experienced creative \"downloads\" where ideas came faster than you could write\n• In deep meditation, thoughts stopped and pure awareness remained — clear, spacious, alive\n• You had a moment of understanding something so deeply that words became irrelevant\n\nThe trap: Over-intellectualization. Getting stuck in ideas ABOUT awakening instead of actually awakening. The Seeker stage trap — collecting spiritual concepts like trophies without embodying them."),
                    AwakeningSection(heading: "Floor 5: The Causal Plane — The Soul's Hard Drive", body: "This is where it gets genuinely hard to put into words, because the causal plane is beyond thought, beyond emotion, beyond form. It's the layer where your soul's entire history is stored.\n\nIf the mental plane is the cloud, the causal plane is the server where ALL the data lives — not just from this life, but (traditions say) from every incarnation. Past, present, and future exist simultaneously here. There's no timeline. No separation between \"you\" and \"your life.\" It's all one pattern.\n\nWhat traditions call it:\n• Hinduism: Karana sharira (the causal body)\n• Buddhism: The seed-consciousness (alaya-vijnana) where karma is stored\n• Theosophy: The higher self / soul level\n• Kabbalah: Neshamah (the divine soul)\n\nYou've glimpsed it when:\n• A near-death experience showed your entire life in a single instant\n• Deep meditation dissolved your sense of being a separate person — just awareness existed\n• You had a prophetic dream or vision that later came true in exact detail\n• Post-Dark Night, you experienced a peace so deep it felt like \"coming home\" to something ancient\n\nThis is the plane where karma lives. Not karma as \"cosmic punishment\" — karma as cause and effect at the soul level. Every choice you've ever made is recorded here. Not to judge you. To teach you.\n\nWhy it matters: The causal plane is where the Dark Night of the Soul does its deepest work. It strips away not just your current identity but your soul-level patterns. That's why it hurts so much. That's also why it transforms so completely.\n\nModern parallel: Transpersonal psychology's concept of the \"superconscious.\" Past-life regression research (Stevenson, Tucker). Near-death experience studies (van Lommel)."),
                ],
                reflectionPrompt: "Have I ever experienced \"knowing\" something without being able to explain how I knew it? Could that be information from a deeper floor?"
            ),
            
            // LESSON 4: Empyrean + Brahmaloka + Naraka (The Highest and The Purifier)
            AwakeningLesson(
                id: "joa_m6_l4",
                number: 4,
                title: "The Summit & The Purifier",
                subtitle: "Floors 6-7: Pure light. Floor B: Where karma burns clean.",
                emoji: "✨",
                sections: [
                    AwakeningSection(heading: "Floor 6: The Empyrean — Pure Light, Pure Love", body: "This is the top floor in the Western map. Dante described it as the final sphere beyond all other heavens — a realm of pure light where divine love moves everything.\n\nThis isn't a place. It's a state of being where every distinction dissolves. Self and other. Human and divine. Here and there. Past and future. All of it merges into infinite, radiant stillness.\n\nWhat traditions call it:\n• Christianity (Dante/mystics): The Empyrean — dwelling of God\n• Neoplatonism: The One — source of all existence\n• Sufism: Baqa — subsistence in God after the ego has been annihilated (fana)\n• Advaita Vedanta: Brahman — the absolute, non-dual reality\n\nThis corresponds to Unity Consciousness (Stage 7). Not as an experience you have — but as what you ARE when every false layer has been burned away.\n\nVery few humans report sustained access. Momentary glimpses happen in deep meditation, near-death experiences, or spontaneous mystical states. Every tradition says the same thing about it: words fail. Language was built for the physical plane. This floor doesn't fit in language.\n\nModern parallel: Non-dual awareness states documented in advanced meditators. Neuroimaging showing dissolution of default mode network (the brain's \"self\" circuitry)."),
                    AwakeningSection(heading: "Floor 7: Brahmaloka — Truth-Consciousness-Bliss", body: "This is the Hindu tradition's highest heaven — the realm of Brahma (the creator aspect of the divine). Pure knowledge. Pure bliss. No karma. No duality.\n\nThe Sanskrit description is sat-chit-ananda:\n• Sat = truth/being (what is absolutely real)\n• Chit = consciousness (pure awareness)\n• Ananda = bliss (not pleasure — a peace beyond pleasure)\n\nThis is where the Yogic paths culminate. Bhakti yoga (devotion) arrives through love. Jnana yoga (knowledge) arrives through inquiry. Both reach the same floor.\n\nImportant nuance: Hindu cosmology says even Brahmaloka is temporary at the cosmic scale — it dissolves at the end of a cosmic cycle (pralaya) and is re-created. Only liberation (moksha) is permanent.\n\nFor our purposes: Brahmaloka represents the peak mystical state described across traditions. The light at the end of the tunnel. The face of God. The dissolution of everything into everything.\n\nModern parallel: Peak experiences in psychedelic research (Griffiths et al., Johns Hopkins). Advanced meditation states where subjects report \"knowing everything\" for brief moments."),
                    AwakeningSection(heading: "The Basement: Naraka — Purification, Not Punishment", body: "Every tradition that describes higher floors also describes lower floors. But here's what they DON'T tell you in Sunday school: the basement is not eternal hell.\n\nNaraka (Hindu/Buddhist) describes temporary realms of purification where the soul processes heavy karma through intense experience. The Garuda Purana describes 21 levels. Buddhism maps 8 hot narakas and 8 cold narakas. Each one is tailored — fire for anger, ice for cold-heartedness.\n\nThe key word: TEMPORARY. The soul enters, processes, and exits — either to rebirth or to higher planes. It's a washing machine, not a prison sentence.\n\nThis maps directly to the Dark Night of the Soul. When you're in Stage 5, it can feel like hell. Literally. Existential despair, loss of identity, feeling abandoned by God/universe/everything. That IS the purification. The old you is burning so the real you can emerge.\n\nWhat traditions call it:\n• Hinduism: Naraka (temporary, overseen by Yama, lord of death/justice)\n• Buddhism: Naraka (temporary, karma-driven, even beings here eventually escape)\n• Christianity (original, not medieval): Purgatory (purification, not damnation)\n• Alchemy: Nigredo (the blackening — the putrefaction stage where everything rots before rebirth)\n• Gnosticism: The lower Archonic spheres (dense, controlling, but escapable through gnosis)\n\nModern parallel: Shadow work in Jungian psychology. Post-traumatic processing. The therapeutic concept of \"healing crisis\" — getting worse before getting better.\n\nThe trap: Taking naraka literally and living in fear. The purpose is purification and education, not punishment. If your tradition taught you eternal hellfire — that's a control mechanism, not cosmology. Every original tradition describes the basement as temporary."),
                ],
                reflectionPrompt: "How does reframing 'hell' as temporary purification rather than eternal punishment change my relationship to suffering — both my own and others'?"
            ),
            
            // LESSON 5: Seeing the Full Map
            AwakeningLesson(
                id: "joa_m6_l5",
                number: 5,
                title: "The Full Map",
                subtitle: "All 8 layers side by side — and what they mean for you",
                emoji: "🗺️",
                sections: [
                    AwakeningSection(heading: "The Building at a Glance", body: "Here's the whole building. Every floor. Every tradition's name for it. Every way you might have already visited.\n\n🏢 FLOOR 7 — Brahmaloka: Truth-Consciousness-Bliss. Hindu highest heaven. Sat-chit-ananda. Beyond karma. Unity.\n\n☀️ FLOOR 6 — Empyrean: Pure light, divine love. Dante, Neoplatonism, Sufism. Non-dual awareness. Stage 7.\n\n🔮 FLOOR 5 — Causal: Soul memory. Karma storage. Past/present/future as one. Deep samadhi, NDEs. Post-Dark Night.\n\n💭 FLOOR 4 — Mental: Living ideas, archetypes, Akashic records. Plato's Forms. Creative downloads. Seeker→Integration.\n\n🌊 FLOOR 3 — Astral: Emotions, dreams, visions. Vivid and wild. Beautiful but deceptive. Lucid dreams, psychedelics.\n\n⚡ FLOOR 2 — Etheric: Life-force energy. Prana, chi, biofield. Tingling, auras, gut feelings. Kundalini highway.\n\n🌍 FLOOR 1 — Physical: Matter, senses, time. Maya, Malkuth, Samsara. Where you are now. The sacred ground floor.\n\n🔥 BASEMENT — Naraka: Purification. Temporary. Burning karma. Dark Night territory. The washing machine.\n\nEvery tradition drew this building. Different architects. Same structure."),
                    AwakeningSection(heading: "What This Means for Your Journey", body: "You're not trying to \"get to\" the top floor. That's the ego talking — \"I want to be enlightened\" is just \"I want a promotion\" wearing a meditation cushion.\n\nThe point is awareness. Knowing the building exists. Recognizing which floor you're experiencing in a given moment.\n\nWhen you dream vividly — that's floor 3. Useful information, but don't get lost there.\n\nWhen energy surges through your body during meditation — that's floor 2. Don't panic. Don't force it. Just ground.\n\nWhen an idea arrives fully formed out of nowhere — that's floor 4. Write it down. Act on it.\n\nWhen the Dark Night strips everything away — that's the basement doing its work. You will come out cleaner.\n\nWhen you feel connected to everything and the boundary between self and world dissolves — that's floors 5-7 saying hello.\n\nThe earthly plane is not the lowest floor in a hierarchy of value. It's the FOUNDATION. Every other floor rests on it. The work happens here. The integration happens here. The awakened person doesn't leave Earth — they bring every floor's awareness INTO their earthly life.\n\nThat's what \"the kingdom of God is within you\" means. All the floors are already inside you. The building is your consciousness."),
                    AwakeningSection(heading: "Cautions", body: "Maps are not the territory. No map is complete. Every tradition drew from their own cultural lens.\n\nLiteral fear: Don't read about naraka and start panicking about being trapped in hell realms. That fear IS an archonic control mechanism — keeping you obedient through terror instead of helping you grow through understanding.\n\nSpiritual tourism: Don't chase experiences on other planes (astral projection, kundalini activation) as entertainment. That's the Seeker trap — collecting spiritual experiences like stamps.\n\nNeglecting the ground floor: The physical plane is where free will exists. Where you make choices. Where relationships, creativity, and service happen. Any path that tells you to abandon Earth is selling escape, not awakening.\n\nPsychological overlap: Intense experiences on any plane can overlap with mental health conditions. If you're experiencing prolonged distress, dissociation, or inability to function — talk to a professional. Maps of consciousness don't replace therapy.\n\nCultural respect: These are living traditions with billions of practitioners. Approach with curiosity and humility, not as a buffet to cherry-pick from."),
                ],
                reflectionPrompt: "If I think of reality as a building with multiple floors — which floor feels like 'home' right now? Which floor am I curious about? Which floor am I avoiding?"
            ),
        ]
    )
}
